import type { Deadline } from "./types";

const compact = (value: string) => value.replaceAll("-", "").replaceAll(":", "");
const nextDay = (date: string) => { const d = new Date(`${date}T12:00:00Z`); d.setUTCDate(d.getUTCDate() + 1); return d.toISOString().slice(0, 10); };
const escapeIcs = (value: string) => value.replaceAll("\\", "\\\\").replaceAll("\n", "\\n").replaceAll(",", "\\,").replaceAll(";", "\\;");

export function calendarData(deadline: Deadline) {
  if (!deadline.normalizedDate) return null;
  const title = deadline.calendarTitle || `Comprendoc: ${deadline.requiredAction}`;
  const description = `Deadline found in your document.\n\nAction:\n${deadline.requiredAction}\n\nOriginal wording:\n“${deadline.sourceText}”\n\nGenerated by Comprendoc. Verify important details against the original document.`;
  const start = deadline.isAllDay ? compact(deadline.normalizedDate) : `${compact(deadline.normalizedDate)}T${compact(deadline.normalizedTime || "09:00")}00`;
  const end = deadline.isAllDay ? compact(nextDay(deadline.normalizedDate)) : start;
  return { title, description, start, end };
}

export function googleCalendarUrl(deadline: Deadline) {
  const data = calendarData(deadline); if (!data) return "#";
  const params = new URLSearchParams({ action: "TEMPLATE", text: data.title, dates: `${data.start}/${data.end}`, details: data.description });
  return `https://calendar.google.com/calendar/render?${params}`;
}

export function outlookCalendarUrl(deadline: Deadline) {
  if (!deadline.normalizedDate) return "#";
  const data = calendarData(deadline)!;
  const start = deadline.isAllDay ? deadline.normalizedDate : `${deadline.normalizedDate}T${deadline.normalizedTime || "09:00"}:00`;
  const params = new URLSearchParams({ path: "/calendar/action/compose", rru: "addevent", subject: data.title, startdt: start, enddt: deadline.isAllDay ? nextDay(deadline.normalizedDate) : start, body: data.description, allday: String(deadline.isAllDay) });
  return `https://outlook.live.com/calendar/0/deeplink/compose?${params}`;
}

export function downloadIcs(deadline: Deadline, reminderMinutes: number | null) {
  const data = calendarData(deadline); if (!data) return;
  const uid = `${deadline.id}-${deadline.normalizedDate}@comprendoc`;
  const reminder = reminderMinutes === null ? "" : `\nBEGIN:VALARM\nTRIGGER:-PT${reminderMinutes}M\nACTION:DISPLAY\nDESCRIPTION:${escapeIcs(data.title)}\nEND:VALARM`;
  const ics = `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Comprendoc//EN\nCALSCALE:GREGORIAN\nBEGIN:VEVENT\nUID:${uid}\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "")}\n${deadline.isAllDay ? `DTSTART;VALUE=DATE:${data.start}\nDTEND;VALUE=DATE:${data.end}` : `DTSTART:${data.start}\nDTEND:${data.end}`}\nSUMMARY:${escapeIcs(data.title)}\nDESCRIPTION:${escapeIcs(data.description)}${reminder}\nEND:VEVENT\nEND:VCALENDAR`;
  const url = URL.createObjectURL(new Blob([ics], { type: "text/calendar;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${deadline.id}.ics`; anchor.click(); URL.revokeObjectURL(url);
}
