export const uiLanguages = [
  { code: "en", label: "English", analysis: "English", dir: "ltr" },
  { code: "zh-CN", label: "简体中文", analysis: "Simplified Chinese", dir: "ltr" },
  { code: "zh-TW", label: "繁體中文", analysis: "Traditional Chinese", dir: "ltr" },
  { code: "es", label: "Español", analysis: "Spanish", dir: "ltr" },
  { code: "fr", label: "Français", analysis: "French", dir: "ltr" },
  { code: "de", label: "Deutsch", analysis: "German", dir: "ltr" },
  { code: "ar", label: "العربية", analysis: "Arabic", dir: "rtl" },
  { code: "pt", label: "Português", analysis: "Portuguese", dir: "ltr" },
  { code: "hi", label: "हिन्दी", analysis: "Hindi", dir: "ltr" },
  { code: "ru", label: "Русский", analysis: "Russian", dir: "ltr" },
  { code: "vi", label: "Tiếng Việt", analysis: "Vietnamese", dir: "ltr" },
  { code: "ja", label: "日本語", analysis: "Japanese", dir: "ltr" },
  { code: "ko", label: "한국어", analysis: "Korean", dir: "ltr" },
] as const;

const interfaceLocaleCodes = ["en", "zh-CN", "zh-TW", "fr", "de", "ko"] as const;
export type Locale = (typeof interfaceLocaleCodes)[number];
export const interfaceLanguages = uiLanguages.filter((language) => interfaceLocaleCodes.some((code) => code === language.code));

const en = {
  privacy: "Privacy", how: "How it works", demo: "Demo", settings: "Settings",
  tagline: "Comprehend the docs. Act on what matters.", hero1: "Understand the paperwork.", hero2: "Know what to do next.",
  heroCopy: "Comprendoc turns complicated documents into clear explanations in your language — and helps you keep track of what matters.",
  demoTitle: "Explore the Comprendoc demo", demoCopy: "This public site uses synthetic examples only. It never accepts documents or makes paid AI requests.", demoButton: "View a demo document",
  drop: "Drop a document here", formats: "PDF, DOCX or TXT · up to 25 MB", choose: "Choose a file", or: "or", paste: "Paste text instead", closePaste: "Close text box",
  pasteLabel: "Paste your document text", pastePlaceholder: "Paste the letter, notice, or form text here…", useText: "Use this text",
  filePrivate: "Your file stays in your browser.", filePrivate2: "Only extracted text is sent for AI analysis.",
  tryExample: "TRY AN EXAMPLE", seeAction: "See Comprendoc in action", synthetic: "Synthetic documents. No personal information.",
  howLabel: "HOW IT WORKS", howTitle: "From red tape to a clear next step", step1: "Add your document", step1Copy: "Upload or paste. Your original file never leaves your browser.", step2: "Choose your language", step2Copy: "Get a natural explanation at the level that works for you.", step3: "Act with confidence", step3Copy: "See deadlines, verify sources, and add dates to your calendar.",
  startOver: "Start over", ready: "DOCUMENT READY", explainHow: "How should we explain it?", extracted: "Your document text was extracted locally. Choose what feels most comfortable.",
  page: "page", pages: "pages", characters: "characters", ocrUsed: "OCR used", textExtracted: "text extracted", ocrWarning: "Some text may have been read incorrectly. Double-check names, dates, amounts, and deadlines against the original.",
  explanationLanguage: "Explanation language", explanationLevel: "Explanation level", simple: "Simple", standard: "Standard", detailed: "Detailed", simpleHint: "Short & clear", standardHint: "Balanced", detailedHint: "More context",
  readyWhen: "Ready when you are.", disclosure: "Extracted document text—not the original file—will be sent to {provider} for analysis.", explain: "Explain this document",
  localWork: "COMPRENDOC IS WORKING LOCALLY", preparing: "Preparing your document", read: "Read document", extract: "Extract text", explainClearly: "Explain clearly", originalPrivate: "Your original file is not uploaded or stored.",
  newDocument: "New document", linked: "Key details are linked to the original text", extraLook: "Take an extra look", whatIs: "WHAT IS THIS?", plain: "In plain language", needKnow: "WHAT YOU NEED TO KNOW", important: "The important points", noPoints: "No important points were found.", deadlines: "DEADLINES", noDeadline: "No deadline found", noActionable: "No actionable deadline was found in this document.", needDo: "WHAT YOU NEED TO DO", nextSteps: "Your next steps", noAction: "No action found in this document", dates: "IMPORTANT DATES", otherDates: "Other dates", money: "MONEY / FEES", amounts: "Amounts mentioned", jargon: "JARGON EXPLAINED", simpler: "Words made simpler", doubleCheck: "THINGS TO DOUBLE-CHECK", uncertain: "Comprendoc is not certain about", checkOriginal: "Check the original", checkCopy: "AI can make mistakes. Verify important dates and requirements against your document.", privateDesign: "Private by design", privateCopy: "No account. No document history. Your original file stayed on this device.",
  sourceText: "ORIGINAL DOCUMENT TEXT", exactWording: "Check the exact wording", viewSource: "View source", addCalendar: "Add to calendar", certainty: "CERTAINTY", exactUnknown: "Exact date cannot be calculated yet.", ifMissed: "If missed", dateRadar: "dates to keep on your radar",
  settingsTitle: "Self-hosted settings", settingsCopy: "Use a server key from OPENAI_API_KEY, or enter your own key for this browser session. Session keys are never saved to disk and clear when the browser session ends.", apiKey: "OpenAI API key", apiPlaceholder: "sk-…", saveSession: "Use for this session", clearKey: "Clear session key", keyReady: "A server-side API key is configured.", keySessionReady: "A session API key is ready.", keyMissing: "Add an API key before analyzing a document.", close: "Close",
  buildForGood: "Build for Good", mainNavigation: "Main navigation", interfaceLanguage: "Interface language", chooseDocument: "Choose a PDF, DOCX, or TXT document", removeDocument: "Remove document", aiProvider: "AI provider", configureProvider: "Configure a provider in Settings", pastedTextName: "Pasted text", pasteFirst: "Paste some document text first.", noProvider: "No AI provider is configured. Open Settings to add one.", readingDocument: "Reading document", readyToExplain: "Ready to explain", documentReadError: "This document could not be read.", lookingForDates: "Looking for important dates", simplifyingDocument: "Simplifying document", translatingDocument: "Translating document", explanationReady: "Explanation ready", explanationError: "The document could not be explained.", formsDescription: "Forms, documents & orientation", incomeDescription: "Income verification request", threeDeadlines: "3 deadlines", relativeDeadline: "relative deadline", timezoneNotStated: "timezone not stated", confidence: "confidence",
  dateUnavailable: "Date unavailable", closeCalendar: "Close calendar options", addToCalendarTitle: "ADD TO CALENDAR", allDayEvent: "All-day event", verifyTimezone: "verify local timezone", remindMe: "Remind me", onTheDay: "On the day", oneDayBefore: "1 day before", threeDaysBefore: "3 days before", oneWeekBefore: "1 week before", noReminder: "No reminder", openNewTab: "Open in a new tab", otherCalendar: "Apple / other calendar", downloadIcs: "Download an .ics file", eventPrivacy: "Only this event’s title, date, action, and source wording are added—not your whole document.",
  backToDemo: "Back to demo", settingsUnavailable: "Settings are unavailable on the public demo", settingsUnavailableCopy: "Clone and self-host Comprendoc to configure your own providers.", backToComprendoc: "Back to Comprendoc", selfHostedConfiguration: "SELF-HOSTED CONFIGURATION", providerVault: "AI provider vault", providerVaultCopy: "Store multiple provider keys encrypted at rest and choose which model handles each document.", encryptedAtRest: "AES-256-GCM encrypted", encryptedAtRestCopy: "Keys are never returned to this page after saving. The database contains ciphertext; the master key remains in your server environment.", unlockProviderSettings: "Unlock provider settings", unlockProviderCopy: "Enter the administrator token configured as COMPRENDOC_ADMIN_TOKEN. It stays in this browser session only.", administratorToken: "Administrator token", unlockSettings: "Unlock settings", loadSettingsError: "Could not load provider settings.", enterProviderKey: "Enter a new {provider} API key.", saveProviderError: "Could not save this provider.", providerSaved: "{provider} saved. The key is encrypted and cannot be displayed.", removeProviderConfirm: "Remove the saved {provider} key? This cannot be undone.", removeProviderError: "Could not remove this provider.", providerRemoved: "{provider} removed.", configuredCount: "{configured} of {total} configured", replaceKeyWarning: "Saving a new key replaces the previous key permanently.", lockSettings: "Lock settings", configured: "Configured", defaultProvider: "default", notConfigured: "Not configured", providerDocumentation: "{provider} documentation", endpoint: "Endpoint", modelId: "Model ID", newApiKey: "New API key (replaces saved key)", apiKeyLabel: "API key", savedKeyHidden: "Saved key is hidden", pasteKey: "Paste key", makeDefault: "Make default provider", replaceKey: "Replace key", saveProvider: "Save provider", removeProvider: "Remove",
  demoStudentTitle: "International student enrollment steps", demoStudentSummary: "Submit the enrollment form, pay the deposit, provide the requested documents, and attend orientation.", demoStudentPlain: "This synthetic notice contains three important dates. Complete the form first, then send the documents, and finally attend orientation.", demoApartmentTitle: "Income verification request", demoApartmentSummary: "Return the income verification form within 10 business days after receiving the notice.", demoApartmentPlain: "The exact due date depends on when the notice was received. Check that date before planning your response.",
  library: "Library", saveDocument: "Save document", savingDocument: "Saving…", saved: "Saved", documentSaved: "This processed document is saved in your encrypted library.", saveDocumentError: "This document could not be saved.", unlockLibraryFirst: "Unlock your library with the administrator token before saving or opening documents.", loadingDocuments: "Loading saved document", loadDocumentError: "This saved document could not be opened.",
  savedDocuments: "SAVED DOCUMENTS", yourLibrary: "Your document library", libraryCopy: "Open previously processed documents without running the AI analysis again. Document content is encrypted at rest.", unlockLibrary: "Unlock your library", unlockLibraryCopy: "Use the same administrator token as provider settings. It remains in this browser session only.", unlockLibraryButton: "Unlock library", lockLibrary: "Lock library", savedCount: "{count} saved documents", loadDocumentsError: "Could not load saved documents.", noSavedDocuments: "Nothing saved yet", noSavedDocumentsCopy: "Process a document, then use Save document on the result page.", addDocument: "Process a document", deadlineCount: "{count} deadlines", openDocument: "Open", deleteDocument: "Delete", deleteDocumentLabel: "Delete {title}", deleteDocumentConfirm: "Delete “{title}”? This cannot be undone.", deleteDocumentError: "This document could not be deleted.", documentDeleted: "Document deleted.", libraryUnavailable: "The library is unavailable on the public demo", libraryUnavailableCopy: "Self-host Comprendoc to save processed documents securely.", selfHostedFooterMeta: "Built for good · No accounts · Encrypted document library",
  footer: "Comprendoc helps you understand documents, but AI can make mistakes. Verify important dates, deadlines, and requirements against the original document.", footerMeta: "Built for good · No accounts · No document storage",
};

type Messages = typeof en;
const translations: Partial<Record<string, Partial<Messages>>> = {
  "zh-CN": { privacy:"隐私",how:"使用方法",demo:"演示",settings:"设置",tagline:"读懂文件，把握要事。",hero1:"看懂复杂文件。",hero2:"清楚下一步该做什么。",heroCopy:"Comprendoc 用你的语言把复杂文件变成清晰说明，并帮你记住重要事项。",demoTitle:"体验 Comprendoc 演示",demoCopy:"此公开网站仅使用合成示例，不接收文件，也不会发起付费 AI 请求。",demoButton:"查看演示文件",drop:"将文件拖到这里",formats:"PDF、DOCX 或 TXT · 最大 25 MB",choose:"选择文件",or:"或",paste:"粘贴文本",closePaste:"关闭文本框",pasteLabel:"粘贴文件文本",pastePlaceholder:"在此粘贴信件、通知或表格文本…",useText:"使用此文本",filePrivate:"文件留在浏览器中。",filePrivate2:"仅提取的文本会发送给 AI 分析。",tryExample:"试用示例",seeAction:"查看 Comprendoc 的效果",synthetic:"合成文件，不含个人信息。",howLabel:"使用方法",howTitle:"从繁文缛节到清晰行动",step1:"添加文件",step1Copy:"上传或粘贴，原始文件不会离开浏览器。",step2:"选择语言",step2Copy:"获得适合你的自然、清晰说明。",step3:"安心行动",step3Copy:"查看截止日期、核对来源并添加到日历。",startOver:"重新开始",ready:"文件已准备",explainHow:"希望我们如何说明？",extracted:"文件文本已在本地提取，请选择合适的方式。",explanationLanguage:"说明语言",explanationLevel:"说明详细程度",simple:"简洁",standard:"标准",detailed:"详细",simpleHint:"短而清楚",standardHint:"平衡",detailedHint:"更多背景",readyWhen:"准备好了。",disclosure:"提取的文本（不是原文件）将发送给 {provider} 分析。",explain:"解释此文件",newDocument:"新文件",linked:"关键细节已链接到原文",extraLook:"请特别核对",whatIs:"这是什么？",plain:"简单说明",needKnow:"你需要知道",important:"重点",deadlines:"截止日期",needDo:"你需要做什么",nextSteps:"下一步",checkOriginal:"核对原文",checkCopy:"AI 可能出错，请对照文件核实重要日期和要求。",privateDesign:"隐私优先",settingsTitle:"自托管设置",settingsCopy:"使用 OPENAI_API_KEY 中的服务器密钥，或输入仅供本次浏览器会话使用的密钥。会话密钥不会写入磁盘，关闭会话后即清除。",apiKey:"OpenAI API 密钥",saveSession:"本次会话使用",clearKey:"清除会话密钥",keyReady:"已配置服务器端 API 密钥。",keySessionReady:"会话 API 密钥已就绪。",keyMissing:"分析文件前请添加 API 密钥。",close:"关闭",footer:"Comprendoc 帮你理解文件，但 AI 可能出错。请对照原文核实重要日期、截止时间和要求。",footerMeta:"为公益而建 · 无账户 · 不存储文件" },
  "zh-TW": { privacy:"隱私權",how:"運作方式",demo:"示範",settings:"設定",tagline:"讀懂文件，掌握重點。",hero1:"看懂複雜文件。",hero2:"清楚下一步該做什麼。",heroCopy:"Comprendoc 用你的語言將複雜文件轉化為清楚易懂的說明，並協助你掌握重要事項。",demoTitle:"體驗 Comprendoc 示範",demoCopy:"此公開網站僅使用合成範例，不接收文件，也不會發出付費 AI 請求。",demoButton:"查看示範文件",drop:"將文件拖放到這裡",formats:"PDF、DOCX 或 TXT · 最大 25 MB",choose:"選擇文件",or:"或",paste:"貼上文字",closePaste:"關閉文字方塊",pasteLabel:"貼上文件文字",pastePlaceholder:"在此貼上信件、通知或表格內容…",useText:"使用此文字",filePrivate:"文件只會留在你的瀏覽器中。",filePrivate2:"只有擷取出的文字會傳送給 AI 分析。",tryExample:"試用範例",seeAction:"看看 Comprendoc 如何運作",synthetic:"合成文件，不含個人資料。",howLabel:"運作方式",howTitle:"從繁瑣文件到清楚的下一步",step1:"加入文件",step1Copy:"上傳或貼上；原始文件不會離開瀏覽器。",step2:"選擇語言",step2Copy:"取得符合你需求、自然易懂的說明。",step3:"安心採取行動",step3Copy:"查看期限、核對來源，並將日期加入行事曆。",startOver:"重新開始",ready:"文件已準備完成",explainHow:"希望我們如何說明？",extracted:"文件文字已在本機擷取，請選擇最適合你的方式。",explanationLanguage:"說明語言",explanationLevel:"說明詳細程度",simple:"簡潔",standard:"標準",detailed:"詳細",simpleHint:"簡短清楚",standardHint:"內容均衡",detailedHint:"更多背景",readyWhen:"準備好了。",disclosure:"擷取出的文字（不是原始文件）將傳送給 {provider} 分析。",explain:"解釋這份文件",newDocument:"新文件",linked:"重要細節已連結至原文",extraLook:"請特別留意",whatIs:"這是什麼？",plain:"白話說明",needKnow:"你需要知道",important:"重要重點",deadlines:"截止期限",needDo:"你需要做什麼",nextSteps:"下一步",checkOriginal:"核對原文",checkCopy:"AI 可能出錯，請對照文件核實重要日期與要求。",privateDesign:"隱私優先設計",footer:"Comprendoc 協助你理解文件，但 AI 可能出錯。請對照原文核實重要日期、期限與要求。",footerMeta:"為公益而建 · 無需帳號 · 不儲存文件" },
  es: { privacy:"Privacidad",how:"Cómo funciona",demo:"Demo",settings:"Ajustes",tagline:"Comprende los documentos. Actúa sobre lo importante.",hero1:"Entiende el papeleo.",hero2:"Sabe qué hacer después.",heroCopy:"Comprendoc convierte documentos complicados en explicaciones claras en tu idioma y te ayuda a seguir lo importante.",demoTitle:"Explora la demo de Comprendoc",demoCopy:"Este sitio público solo usa ejemplos sintéticos. No acepta documentos ni realiza solicitudes de IA de pago.",demoButton:"Ver un documento de muestra",drop:"Suelta un documento aquí",choose:"Elegir archivo",or:"o",paste:"Pegar texto",closePaste:"Cerrar texto",filePrivate:"Tu archivo permanece en el navegador.",filePrivate2:"Solo el texto extraído se envía para análisis.",tryExample:"PRUEBA UN EJEMPLO",seeAction:"Mira Comprendoc en acción",synthetic:"Documentos sintéticos. Sin datos personales.",howLabel:"CÓMO FUNCIONA",howTitle:"Del papeleo al siguiente paso claro",step1:"Añade tu documento",step1Copy:"Sube o pega. El archivo original no sale del navegador.",step2:"Elige tu idioma",step2Copy:"Recibe una explicación natural al nivel que prefieras.",step3:"Actúa con confianza",step3Copy:"Ve plazos, verifica fuentes y añade fechas al calendario.",startOver:"Empezar de nuevo",ready:"DOCUMENTO LISTO",explainHow:"¿Cómo debemos explicarlo?",extracted:"El texto se extrajo localmente. Elige lo que te resulte más cómodo.",explanationLanguage:"Idioma de la explicación",explanationLevel:"Nivel de explicación",simple:"Simple",standard:"Estándar",detailed:"Detallado",readyWhen:"Cuando quieras.",disclosure:"El texto extraído—no el archivo original—se enviará a OpenAI.",explain:"Explicar este documento",newDocument:"Nuevo documento",linked:"Los detalles clave enlazan con el texto original",extraLook:"Revísalo con atención",whatIs:"¿QUÉ ES ESTO?",plain:"En lenguaje sencillo",needKnow:"LO QUE DEBES SABER",important:"Los puntos importantes",deadlines:"PLAZOS",needDo:"LO QUE DEBES HACER",nextSteps:"Tus próximos pasos",checkOriginal:"Comprueba el original",checkCopy:"La IA puede equivocarse. Verifica fechas y requisitos en el documento.",privateDesign:"Privado por diseño",settingsTitle:"Ajustes de alojamiento propio",settingsCopy:"Usa la clave del servidor en OPENAI_API_KEY o introduce una clave solo para esta sesión. Nunca se guarda en disco.",apiKey:"Clave API de OpenAI",saveSession:"Usar en esta sesión",clearKey:"Borrar clave de sesión",keyReady:"Hay una clave API configurada en el servidor.",keySessionReady:"La clave de sesión está lista.",keyMissing:"Añade una clave API antes de analizar.",close:"Cerrar",footer:"Comprendoc ayuda a entender documentos, pero la IA puede equivocarse. Verifica fechas, plazos y requisitos con el original.",footerMeta:"Creado para el bien · Sin cuentas · Sin almacenar documentos" },
  fr: { privacy:"Confidentialité",how:"Fonctionnement",demo:"Démo",settings:"Réglages",tagline:"Comprenez les documents. Agissez sur l’essentiel.",hero1:"Comprenez les démarches.",hero2:"Sachez quoi faire ensuite.",heroCopy:"Comprendoc transforme les documents complexes en explications claires dans votre langue et suit l’essentiel.",demoTitle:"Explorez la démo Comprendoc",demoCopy:"Ce site public utilise uniquement des exemples fictifs. Aucun document ni appel IA payant.",demoButton:"Voir un document de démo",drop:"Déposez un document ici",choose:"Choisir un fichier",or:"ou",paste:"Coller du texte",filePrivate:"Votre fichier reste dans le navigateur.",filePrivate2:"Seul le texte extrait est envoyé pour analyse.",tryExample:"ESSAYER UN EXEMPLE",seeAction:"Découvrez Comprendoc",synthetic:"Documents fictifs. Aucune donnée personnelle.",howLabel:"FONCTIONNEMENT",howTitle:"Des formalités à une prochaine étape claire",step1:"Ajoutez votre document",step1Copy:"Importez ou collez. L’original ne quitte jamais le navigateur.",step2:"Choisissez votre langue",step2Copy:"Obtenez une explication naturelle au niveau adapté.",step3:"Agissez en confiance",step3Copy:"Repérez les échéances, vérifiez les sources et ajoutez les dates au calendrier.",startOver:"Recommencer",ready:"DOCUMENT PRÊT",explainHow:"Comment devons-nous l’expliquer ?",extracted:"Le texte a été extrait localement. Choisissez ce qui vous convient.",explanationLanguage:"Langue de l’explication",explanationLevel:"Niveau d’explication",simple:"Simple",standard:"Standard",detailed:"Détaillé",readyWhen:"Quand vous voulez.",disclosure:"Le texte extrait—pas le fichier original—sera envoyé à OpenAI.",explain:"Expliquer ce document",newDocument:"Nouveau document",linked:"Les détails clés sont reliés au texte original",extraLook:"Vérifiez attentivement",whatIs:"QU’EST-CE QUE C’EST ?",plain:"En langage clair",needKnow:"À RETENIR",important:"Les points importants",deadlines:"ÉCHÉANCES",needDo:"CE QUE VOUS DEVEZ FAIRE",nextSteps:"Vos prochaines étapes",checkOriginal:"Vérifiez l’original",privateDesign:"Confidentiel par conception",settingsTitle:"Réglages auto-hébergés",settingsCopy:"Utilisez la clé serveur OPENAI_API_KEY ou saisissez une clé pour cette session uniquement. Elle n’est jamais enregistrée sur disque.",apiKey:"Clé API OpenAI",saveSession:"Utiliser pour cette session",clearKey:"Effacer la clé",keyReady:"Une clé API serveur est configurée.",keySessionReady:"La clé de session est prête.",keyMissing:"Ajoutez une clé API avant l’analyse.",close:"Fermer",footer:"Comprendoc aide à comprendre les documents, mais l’IA peut se tromper. Vérifiez les dates, délais et exigences dans l’original.",footerMeta:"Conçu pour le bien · Sans compte · Aucun document stocké" },
  ar: { privacy:"الخصوصية",how:"كيف يعمل",demo:"عرض تجريبي",settings:"الإعدادات",tagline:"افهم المستندات. وتصرف فيما يهم.",hero1:"افهم الأوراق المعقدة.",hero2:"واعرف خطوتك التالية.",heroCopy:"يحوّل Comprendoc المستندات المعقدة إلى شرح واضح بلغتك ويساعدك على متابعة ما يهم.",demoTitle:"استكشف عرض Comprendoc",demoCopy:"يستخدم هذا الموقع العام أمثلة اصطناعية فقط ولا يقبل مستندات أو يجري طلبات ذكاء اصطناعي مدفوعة.",demoButton:"عرض مستند تجريبي",drop:"أفلت مستندًا هنا",choose:"اختر ملفًا",or:"أو",paste:"الصق نصًا",filePrivate:"يبقى ملفك في متصفحك.",filePrivate2:"يُرسل النص المستخرج فقط للتحليل.",tryExample:"جرّب مثالًا",seeAction:"شاهد Comprendoc أثناء العمل",synthetic:"مستندات اصطناعية بلا معلومات شخصية.",howLabel:"كيف يعمل",howTitle:"من التعقيد إلى خطوة تالية واضحة",step1:"أضف مستندك",step1Copy:"ارفع أو الصق. الملف الأصلي لا يغادر المتصفح.",step2:"اختر لغتك",step2Copy:"احصل على شرح طبيعي بالمستوى المناسب لك.",step3:"تصرّف بثقة",step3Copy:"شاهد المواعيد وتحقق من المصادر وأضف التواريخ إلى التقويم.",startOver:"ابدأ من جديد",ready:"المستند جاهز",explainHow:"كيف نشرحه؟",extracted:"استُخرج النص محليًا. اختر ما يناسبك.",explanationLanguage:"لغة الشرح",explanationLevel:"مستوى الشرح",simple:"بسيط",standard:"متوسط",detailed:"مفصل",readyWhen:"جاهز عندما تكون جاهزًا.",disclosure:"سيُرسل النص المستخرج—وليس الملف الأصلي—إلى OpenAI للتحليل.",explain:"اشرح هذا المستند",newDocument:"مستند جديد",linked:"التفاصيل المهمة مرتبطة بالنص الأصلي",extraLook:"ألقِ نظرة إضافية",whatIs:"ما هذا؟",plain:"بلغة بسيطة",needKnow:"ما تحتاج إلى معرفته",important:"النقاط المهمة",deadlines:"المواعيد النهائية",needDo:"ما عليك فعله",nextSteps:"خطواتك التالية",checkOriginal:"راجع الأصل",privateDesign:"خصوصية مدمجة",settingsTitle:"إعدادات الاستضافة الذاتية",settingsCopy:"استخدم مفتاح الخادم OPENAI_API_KEY أو أدخل مفتاحًا لهذه الجلسة فقط. لا يُحفظ على القرص.",apiKey:"مفتاح OpenAI API",saveSession:"استخدم لهذه الجلسة",clearKey:"امسح مفتاح الجلسة",keyReady:"تم إعداد مفتاح API على الخادم.",keySessionReady:"مفتاح الجلسة جاهز.",keyMissing:"أضف مفتاح API قبل التحليل.",close:"إغلاق",footer:"يساعدك Comprendoc على فهم المستندات، لكن الذكاء الاصطناعي قد يخطئ. تحقق من التواريخ والمتطلبات في الأصل.",footerMeta:"صُمم للخير · بلا حسابات · بلا تخزين للمستندات" },
  pt: { privacy:"Privacidade",how:"Como funciona",demo:"Demo",settings:"Configurações",tagline:"Compreenda os documentos. Aja no que importa.",hero1:"Entenda a papelada.",hero2:"Saiba o que fazer a seguir.",heroCopy:"O Comprendoc transforma documentos complicados em explicações claras no seu idioma e acompanha o que importa.",demoTitle:"Explore a demonstração",demoCopy:"Este site público usa apenas exemplos sintéticos. Não aceita documentos nem faz solicitações pagas de IA.",demoButton:"Ver documento de demonstração",drop:"Solte um documento aqui",choose:"Escolher arquivo",or:"ou",paste:"Colar texto",filePrivate:"Seu arquivo fica no navegador.",filePrivate2:"Só o texto extraído é enviado para análise.",tryExample:"EXPERIMENTE UM EXEMPLO",seeAction:"Veja o Comprendoc em ação",synthetic:"Documentos sintéticos. Sem dados pessoais.",howLabel:"COMO FUNCIONA",howTitle:"Da burocracia ao próximo passo",step1:"Adicione seu documento",step1Copy:"Envie ou cole. O arquivo original não sai do navegador.",step2:"Escolha seu idioma",step2Copy:"Receba uma explicação natural no nível ideal.",step3:"Aja com confiança",step3Copy:"Veja prazos, confira fontes e adicione datas ao calendário.",startOver:"Recomeçar",ready:"DOCUMENTO PRONTO",explainHow:"Como devemos explicar?",extracted:"O texto foi extraído localmente. Escolha o que for melhor.",explanationLanguage:"Idioma da explicação",explanationLevel:"Nível da explicação",simple:"Simples",standard:"Padrão",detailed:"Detalhado",readyWhen:"Quando você estiver pronto.",disclosure:"O texto extraído—não o arquivo original—será enviado à OpenAI.",explain:"Explicar este documento",newDocument:"Novo documento",linked:"Detalhes importantes estão ligados ao texto original",extraLook:"Confira com atenção",whatIs:"O QUE É ISTO?",plain:"Em linguagem simples",needKnow:"O QUE VOCÊ PRECISA SABER",important:"Pontos importantes",deadlines:"PRAZOS",needDo:"O QUE VOCÊ PRECISA FAZER",nextSteps:"Próximos passos",checkOriginal:"Confira o original",privateDesign:"Privacidade por design",settingsTitle:"Configurações auto-hospedadas",settingsCopy:"Use a chave do servidor OPENAI_API_KEY ou informe uma chave só para esta sessão. Ela nunca é salva em disco.",apiKey:"Chave da API OpenAI",saveSession:"Usar nesta sessão",clearKey:"Limpar chave",keyReady:"Uma chave de API está configurada no servidor.",keySessionReady:"A chave da sessão está pronta.",keyMissing:"Adicione uma chave antes de analisar.",close:"Fechar",footer:"O Comprendoc ajuda a entender documentos, mas a IA pode errar. Confira datas, prazos e exigências no original.",footerMeta:"Feito para o bem · Sem contas · Sem armazenar documentos" },
};

// Closely related locales intentionally fall back to English for any untranslated
// secondary label while retaining fully localized navigation and primary flows.
translations.de = { privacy:"Datenschutz",how:"So funktioniert es",demo:"Demo",settings:"Einstellungen",tagline:"Dokumente verstehen. Das Wichtige erledigen.",hero1:"Den Papierkram verstehen.",hero2:"Wissen, was als Nächstes zu tun ist.",heroCopy:"Comprendoc verwandelt komplizierte Dokumente in klare Erklärungen in deiner Sprache und hilft dir, das Wichtige im Blick zu behalten.",demoTitle:"Comprendoc-Demo entdecken",demoCopy:"Diese öffentliche Website verwendet nur synthetische Beispiele. Sie nimmt keine Dokumente an und sendet keine kostenpflichtigen KI-Anfragen.",demoButton:"Demodokument ansehen",drop:"Dokument hier ablegen",formats:"PDF, DOCX oder TXT · bis zu 25 MB",choose:"Datei auswählen",or:"oder",paste:"Text einfügen",closePaste:"Textfeld schließen",pasteLabel:"Dokumenttext einfügen",pastePlaceholder:"Brief, Bescheid oder Formulartext hier einfügen…",useText:"Diesen Text verwenden",filePrivate:"Deine Datei bleibt im Browser.",filePrivate2:"Nur der extrahierte Text wird zur KI-Analyse gesendet.",tryExample:"BEISPIEL AUSPROBIEREN",seeAction:"Comprendoc in Aktion",synthetic:"Synthetische Dokumente. Keine personenbezogenen Daten.",howLabel:"SO FUNKTIONIERT ES",howTitle:"Vom Papierkram zum klaren nächsten Schritt",step1:"Dokument hinzufügen",step1Copy:"Hochladen oder einfügen. Die Originaldatei verlässt den Browser nicht.",step2:"Sprache auswählen",step2Copy:"Eine natürliche Erklärung im passenden Detailgrad erhalten.",step3:"Sicher handeln",step3Copy:"Fristen erkennen, Quellen prüfen und Termine zum Kalender hinzufügen.",startOver:"Neu beginnen",ready:"DOKUMENT BEREIT",explainHow:"Wie sollen wir es erklären?",extracted:"Der Dokumenttext wurde lokal extrahiert. Wähle die passende Darstellung.",explanationLanguage:"Sprache der Erklärung",explanationLevel:"Detailgrad",simple:"Einfach",standard:"Standard",detailed:"Ausführlich",simpleHint:"Kurz und klar",standardHint:"Ausgewogen",detailedHint:"Mehr Kontext",readyWhen:"Bereit, wenn du es bist.",disclosure:"Der extrahierte Text – nicht die Originaldatei – wird zur Analyse an {provider} gesendet.",explain:"Dokument erklären",newDocument:"Neues Dokument",linked:"Wichtige Details sind mit dem Originaltext verknüpft",extraLook:"Bitte besonders prüfen",whatIs:"WAS IST DAS?",plain:"Einfach erklärt",needKnow:"WAS DU WISSEN MUSST",important:"Die wichtigsten Punkte",deadlines:"FRISTEN",needDo:"WAS DU TUN MUSST",nextSteps:"Deine nächsten Schritte",checkOriginal:"Original prüfen",checkCopy:"KI kann Fehler machen. Prüfe wichtige Daten und Anforderungen im Originaldokument.",privateDesign:"Datenschutz von Grund auf",footer:"Comprendoc hilft beim Verstehen von Dokumenten, aber KI kann Fehler machen. Prüfe wichtige Daten, Fristen und Anforderungen im Original.",footerMeta:"Für das Gute entwickelt · Keine Konten · Keine Dokumentenspeicherung" };
translations.hi = { privacy:"गोपनीयता",how:"यह कैसे काम करता है",demo:"डेमो",settings:"सेटिंग्स",tagline:"दस्तावेज़ समझें। ज़रूरी काम करें।",hero1:"कागज़ात को समझें।",hero2:"अगला कदम जानें।",heroCopy:"Comprendoc कठिन दस्तावेज़ों को आपकी भाषा में साफ़ समझाता है।",demoTitle:"Comprendoc डेमो देखें",demoCopy:"यह सार्वजनिक साइट केवल नकली उदाहरण दिखाती है। कोई दस्तावेज़ या सशुल्क AI अनुरोध नहीं।",demoButton:"डेमो दस्तावेज़ देखें",choose:"फ़ाइल चुनें",tryExample:"उदाहरण आज़माएँ",seeAction:"Comprendoc को काम करते देखें",startOver:"फिर से शुरू करें",explanationLanguage:"समझाने की भाषा",explanationLevel:"विवरण स्तर",explain:"दस्तावेज़ समझाएँ",settingsTitle:"सेल्फ-होस्टेड सेटिंग्स",apiKey:"OpenAI API कुंजी",saveSession:"इस सत्र में उपयोग करें",clearKey:"सत्र कुंजी हटाएँ",keyMissing:"विश्लेषण से पहले API कुंजी जोड़ें।",close:"बंद करें" };
translations.ru = { privacy:"Конфиденциальность",how:"Как это работает",demo:"Демо",settings:"Настройки",tagline:"Поймите документы. Сделайте главное.",hero1:"Разберитесь в документах.",hero2:"Узнайте, что делать дальше.",heroCopy:"Comprendoc превращает сложные документы в понятные объяснения на вашем языке.",demoTitle:"Демо Comprendoc",demoCopy:"Публичный сайт показывает только искусственные примеры. Загрузка документов и платные запросы ИИ отключены.",demoButton:"Открыть демо-документ",choose:"Выбрать файл",tryExample:"ПОПРОБОВАТЬ ПРИМЕР",seeAction:"Comprendoc в действии",startOver:"Начать сначала",explanationLanguage:"Язык объяснения",explanationLevel:"Уровень объяснения",explain:"Объяснить документ",newDocument:"Новый документ",settingsTitle:"Настройки самостоятельного хостинга",apiKey:"Ключ OpenAI API",saveSession:"Использовать в этой сессии",clearKey:"Удалить ключ",keyMissing:"Добавьте ключ API перед анализом.",close:"Закрыть" };
translations.vi = { privacy:"Quyền riêng tư",how:"Cách hoạt động",demo:"Bản thử",settings:"Cài đặt",tagline:"Hiểu tài liệu. Hành động đúng việc.",hero1:"Hiểu giấy tờ.",hero2:"Biết bước tiếp theo.",heroCopy:"Comprendoc biến tài liệu phức tạp thành lời giải thích rõ ràng bằng ngôn ngữ của bạn.",demoTitle:"Khám phá bản thử Comprendoc",demoCopy:"Trang công khai này chỉ dùng ví dụ tổng hợp, không nhận tài liệu hay gọi AI trả phí.",demoButton:"Xem tài liệu mẫu",choose:"Chọn tệp",tryExample:"THỬ MỘT VÍ DỤ",seeAction:"Xem Comprendoc hoạt động",startOver:"Bắt đầu lại",explanationLanguage:"Ngôn ngữ giải thích",explanationLevel:"Mức giải thích",explain:"Giải thích tài liệu",settingsTitle:"Cài đặt tự lưu trữ",apiKey:"Khóa OpenAI API",saveSession:"Dùng trong phiên này",clearKey:"Xóa khóa phiên",keyMissing:"Hãy thêm khóa API trước khi phân tích.",close:"Đóng" };
translations.ja = { privacy:"プライバシー",how:"使い方",demo:"デモ",settings:"設定",tagline:"書類を理解し、大切なことに行動を。",hero1:"複雑な書類を理解。",hero2:"次にすることが分かる。",heroCopy:"Comprendoc は複雑な書類をあなたの言語で分かりやすく説明します。",demoTitle:"Comprendoc デモを体験",demoCopy:"公開サイトでは合成サンプルのみを使用し、書類の受付や有料 AI リクエストは行いません。",demoButton:"デモ書類を見る",choose:"ファイルを選ぶ",tryExample:"サンプルを試す",seeAction:"Comprendoc の動作を見る",startOver:"最初から",explanationLanguage:"説明の言語",explanationLevel:"説明レベル",simple:"簡潔",standard:"標準",detailed:"詳細",explain:"この書類を説明",newDocument:"新しい書類",settingsTitle:"セルフホスト設定",apiKey:"OpenAI API キー",saveSession:"このセッションで使用",clearKey:"セッションキーを削除",keyMissing:"分析前に API キーを追加してください。",close:"閉じる" };
translations.ko = { privacy:"개인정보",how:"사용 방법",demo:"데모",settings:"설정",tagline:"문서를 이해하고 중요한 일에 집중하세요.",hero1:"복잡한 서류를 이해하세요.",hero2:"다음 할 일을 확인하세요.",heroCopy:"Comprendoc은 복잡한 문서를 사용자의 언어로 명확하게 설명합니다.",demoTitle:"Comprendoc 데모 체험",demoCopy:"공개 사이트는 합성 예시만 사용하며 문서를 받거나 유료 AI 요청을 하지 않습니다.",demoButton:"데모 문서 보기",choose:"파일 선택",tryExample:"예시 사용해 보기",seeAction:"Comprendoc 작동 방식 보기",startOver:"다시 시작",explanationLanguage:"설명 언어",explanationLevel:"설명 수준",simple:"간단히",standard:"표준",detailed:"자세히",explain:"문서 설명하기",newDocument:"새 문서",settingsTitle:"셀프 호스팅 설정",apiKey:"OpenAI API 키",saveSession:"이 세션에서 사용",clearKey:"세션 키 삭제",keyMissing:"분석 전에 API 키를 추가하세요.",close:"닫기" };
translations.ko = { ...translations.ko, readyWhen:"준비되었습니다.",disclosure:"추출된 문서 텍스트(원본 파일이 아님)는 분석을 위해 {provider}에 전송됩니다." };

translations["zh-CN"] = { ...translations["zh-CN"],page:"页",pages:"页",characters:"个字符",ocrUsed:"已使用 OCR",textExtracted:"已提取文本",ocrWarning:"部分文字可能识别有误。请对照原文核对姓名、日期、金额和截止时间。",localWork:"COMPRENDOC 正在本地处理",preparing:"正在准备文件",read:"读取文件",extract:"提取文本",explainClearly:"清晰解释",originalPrivate:"原始文件不会被上传或存储。",noPoints:"未找到重要事项。",noDeadline:"未找到截止时间",noActionable:"此文件中没有可执行的截止时间。",noAction:"此文件中没有需要采取的行动",dates:"重要日期",otherDates:"其他日期",money:"金额 / 费用",amounts:"提到的金额",jargon:"术语解释",simpler:"用更简单的话说明",doubleCheck:"需要再次核对",uncertain:"Comprendoc 无法确定的内容",privateCopy:"无需账户，不保留文件历史，原始文件始终留在此设备上。",sourceText:"原始文件文本",exactWording:"查看原文措辞",viewSource:"查看原文",addCalendar:"添加到日历",certainty:"确定程度",exactUnknown:"目前无法计算确切日期。",ifMissed:"如果错过",dateRadar:"个需要留意的日期",apiPlaceholder:"API 密钥" };
translations["zh-TW"] = { ...translations["zh-TW"],page:"頁",pages:"頁",characters:"個字元",ocrUsed:"已使用 OCR",textExtracted:"已擷取文字",ocrWarning:"部分文字可能辨識有誤。請對照原文核對姓名、日期、金額與截止時間。",localWork:"COMPRENDOC 正在本機處理",preparing:"正在準備文件",read:"讀取文件",extract:"擷取文字",explainClearly:"清楚說明",originalPrivate:"原始文件不會被上傳或儲存。",noPoints:"找不到重要事項。",noDeadline:"找不到截止期限",noActionable:"此文件中沒有可執行的截止期限。",noAction:"此文件中沒有需要採取的行動",dates:"重要日期",otherDates:"其他日期",money:"金額 / 費用",amounts:"提及的金額",jargon:"術語解釋",simpler:"用更簡單的方式說明",doubleCheck:"需要再次核對",uncertain:"Comprendoc 無法確定的內容",privateCopy:"無需帳號、不保留文件記錄，原始文件始終留在此裝置上。",sourceText:"原始文件文字",exactWording:"查看原文措辭",viewSource:"查看原文",addCalendar:"加入行事曆",certainty:"確定程度",exactUnknown:"目前無法計算確切日期。",ifMissed:"如果錯過",dateRadar:"個需要留意的日期",settingsTitle:"自架設定",settingsCopy:"在伺服器上安全設定 AI 供應商。",apiKey:"API 金鑰",apiPlaceholder:"API 金鑰",saveSession:"儲存",clearKey:"清除金鑰",keyReady:"已設定伺服器金鑰。",keySessionReady:"金鑰已就緒。",keyMissing:"分析前請先加入 API 金鑰。",close:"關閉" };
translations.fr = { ...translations.fr,formats:"PDF, DOCX ou TXT · 25 Mo maximum",closePaste:"Fermer la zone de texte",pasteLabel:"Collez le texte du document",pastePlaceholder:"Collez ici le texte de la lettre, de l’avis ou du formulaire…",useText:"Utiliser ce texte",page:"page",pages:"pages",characters:"caractères",ocrUsed:"OCR utilisé",textExtracted:"texte extrait",ocrWarning:"Certains passages peuvent avoir été mal reconnus. Vérifiez les noms, dates, montants et échéances dans l’original.",simpleHint:"Court et clair",standardHint:"Équilibré",detailedHint:"Plus de contexte",localWork:"COMPRENDOC TRAVAILLE EN LOCAL",preparing:"Préparation du document",read:"Lire le document",extract:"Extraire le texte",explainClearly:"Expliquer clairement",originalPrivate:"Votre fichier original n’est ni importé ni stocké.",noPoints:"Aucun point important trouvé.",noDeadline:"Aucune échéance trouvée",noActionable:"Aucune échéance exploitable n’a été trouvée.",noAction:"Aucune action trouvée",dates:"DATES IMPORTANTES",otherDates:"Autres dates",money:"MONTANTS / FRAIS",amounts:"Montants mentionnés",jargon:"TERMES EXPLIQUÉS",simpler:"Des mots plus simples",doubleCheck:"À VÉRIFIER",uncertain:"Ce dont Comprendoc n’est pas certain",checkCopy:"L’IA peut se tromper. Vérifiez les dates et exigences importantes dans le document.",privateCopy:"Aucun compte ni historique. Le fichier original est resté sur cet appareil.",sourceText:"TEXTE DU DOCUMENT ORIGINAL",exactWording:"Vérifier la formulation exacte",viewSource:"Voir la source",addCalendar:"Ajouter au calendrier",certainty:"CERTITUDE",exactUnknown:"La date exacte ne peut pas encore être calculée.",ifMissed:"En cas de retard",dateRadar:"dates à surveiller",apiPlaceholder:"Clé API" };
translations.de = { ...translations.de,page:"Seite",pages:"Seiten",characters:"Zeichen",ocrUsed:"OCR verwendet",textExtracted:"Text extrahiert",ocrWarning:"Einige Texte wurden möglicherweise falsch erkannt. Prüfe Namen, Daten, Beträge und Fristen im Original.",localWork:"COMPRENDOC ARBEITET LOKAL",preparing:"Dokument wird vorbereitet",read:"Dokument lesen",extract:"Text extrahieren",explainClearly:"Klar erklären",originalPrivate:"Die Originaldatei wird weder hochgeladen noch gespeichert.",noPoints:"Keine wichtigen Punkte gefunden.",noDeadline:"Keine Frist gefunden",noActionable:"In diesem Dokument wurde keine umsetzbare Frist gefunden.",noAction:"Keine erforderliche Aktion gefunden",dates:"WICHTIGE DATEN",otherDates:"Weitere Daten",money:"BETRÄGE / GEBÜHREN",amounts:"Genannte Beträge",jargon:"BEGRIFFE ERKLÄRT",simpler:"Einfacher formuliert",doubleCheck:"NOCH EINMAL PRÜFEN",uncertain:"Wobei Comprendoc unsicher ist",privateCopy:"Kein Konto, kein Dokumentverlauf. Die Originaldatei blieb auf diesem Gerät.",sourceText:"TEXT DES ORIGINALDOKUMENTS",exactWording:"Genauen Wortlaut prüfen",viewSource:"Quelle ansehen",addCalendar:"Zum Kalender hinzufügen",certainty:"SICHERHEIT",exactUnknown:"Das genaue Datum kann noch nicht berechnet werden.",ifMissed:"Bei Versäumnis",dateRadar:"wichtige Termine",settingsTitle:"Self-Hosting-Einstellungen",settingsCopy:"KI-Anbieter sicher auf deinem Server konfigurieren.",apiKey:"API-Schlüssel",apiPlaceholder:"API-Schlüssel",saveSession:"Speichern",clearKey:"Schlüssel löschen",keyReady:"Ein Serverschlüssel ist eingerichtet.",keySessionReady:"Der Schlüssel ist bereit.",keyMissing:"Füge vor der Analyse einen API-Schlüssel hinzu.",close:"Schließen" };
translations.ko = { ...translations.ko,drop:"문서를 여기에 놓으세요",formats:"PDF, DOCX 또는 TXT · 최대 25MB",or:"또는",paste:"텍스트 붙여넣기",closePaste:"텍스트 상자 닫기",pasteLabel:"문서 텍스트 붙여넣기",pastePlaceholder:"편지, 안내문 또는 양식 텍스트를 여기에 붙여넣으세요…",useText:"이 텍스트 사용",filePrivate:"파일은 브라우저에만 남습니다.",filePrivate2:"추출된 텍스트만 AI 분석을 위해 전송됩니다.",synthetic:"합성 문서이며 개인정보가 없습니다.",howLabel:"사용 방법",howTitle:"복잡한 서류에서 명확한 다음 단계로",step1:"문서 추가",step1Copy:"업로드하거나 붙여넣으세요. 원본 파일은 브라우저를 벗어나지 않습니다.",step2:"언어 선택",step2Copy:"원하는 수준의 자연스러운 설명을 받으세요.",step3:"안심하고 실행",step3Copy:"마감일과 출처를 확인하고 날짜를 달력에 추가하세요.",ready:"문서 준비 완료",explainHow:"어떻게 설명할까요?",extracted:"문서 텍스트가 로컬에서 추출되었습니다. 원하는 방식을 선택하세요.",page:"페이지",pages:"페이지",characters:"자",ocrUsed:"OCR 사용",textExtracted:"텍스트 추출",ocrWarning:"일부 텍스트가 잘못 인식되었을 수 있습니다. 이름, 날짜, 금액, 마감일을 원본과 확인하세요.",simpleHint:"짧고 명확하게",standardHint:"균형 있게",detailedHint:"더 많은 맥락",localWork:"COMPRENDOC이 로컬에서 작업 중",preparing:"문서 준비 중",read:"문서 읽기",extract:"텍스트 추출",explainClearly:"명확하게 설명",originalPrivate:"원본 파일은 업로드되거나 저장되지 않습니다.",linked:"주요 세부 정보가 원문과 연결되어 있습니다",extraLook:"한 번 더 확인하세요",whatIs:"이 문서는 무엇인가요?",plain:"쉬운 말로",needKnow:"알아야 할 내용",important:"중요한 사항",noPoints:"중요한 사항을 찾지 못했습니다.",deadlines:"마감일",noDeadline:"마감일 없음",noActionable:"실행 가능한 마감일을 찾지 못했습니다.",needDo:"해야 할 일",nextSteps:"다음 단계",noAction:"필요한 조치가 없습니다",dates:"중요한 날짜",otherDates:"기타 날짜",money:"금액 / 수수료",amounts:"언급된 금액",jargon:"용어 설명",simpler:"더 쉬운 표현",doubleCheck:"다시 확인할 사항",uncertain:"Comprendoc이 확신하지 못하는 내용",checkOriginal:"원문 확인",checkCopy:"AI는 실수할 수 있습니다. 중요한 날짜와 요구 사항을 원문에서 확인하세요.",privateDesign:"개인정보 보호 설계",privateCopy:"계정과 문서 기록이 없습니다. 원본 파일은 이 기기에 남아 있습니다.",sourceText:"원본 문서 텍스트",exactWording:"정확한 문구 확인",viewSource:"원문 보기",addCalendar:"달력에 추가",certainty:"확실성",exactUnknown:"정확한 날짜를 아직 계산할 수 없습니다.",ifMissed:"놓친 경우",dateRadar:"개의 확인할 날짜",settingsCopy:"서버에서 AI 제공업체를 안전하게 설정하세요.",apiPlaceholder:"API 키",keyReady:"서버 키가 설정되었습니다.",keySessionReady:"키가 준비되었습니다.",footer:"Comprendoc은 문서를 이해하는 데 도움을 주지만 AI는 실수할 수 있습니다. 중요한 날짜, 마감일, 요구 사항을 원문에서 확인하세요.",footerMeta:"공익을 위해 제작 · 계정 없음 · 문서 저장 없음" };

translations["zh-CN"] = { ...translations["zh-CN"],buildForGood:"公益项目",mainNavigation:"主导航",interfaceLanguage:"界面语言",chooseDocument:"选择 PDF、DOCX 或 TXT 文件",removeDocument:"移除文件",aiProvider:"AI 服务商",configureProvider:"请先在设置中配置服务商",pastedTextName:"粘贴的文本",pasteFirst:"请先粘贴一些文件文本。",noProvider:"尚未配置 AI 服务商。请前往设置添加。",readingDocument:"正在读取文件",readyToExplain:"已准备好解释",documentReadError:"无法读取此文件。",lookingForDates:"正在查找重要日期",simplifyingDocument:"正在简化文件",translatingDocument:"正在翻译文件",explanationReady:"解释已完成",explanationError:"无法解释此文件。",formsDescription:"表格、文件和说明会",incomeDescription:"收入证明请求",threeDeadlines:"3 个截止时间",relativeDeadline:"相对期限",timezoneNotStated:"未注明时区",confidence:"可信度",dateUnavailable:"日期不可用",closeCalendar:"关闭日历选项",addToCalendarTitle:"添加到日历",allDayEvent:"全天事件",verifyTimezone:"请核对本地时区",remindMe:"提醒我",onTheDay:"当天",oneDayBefore:"提前 1 天",threeDaysBefore:"提前 3 天",oneWeekBefore:"提前 1 周",noReminder:"不提醒",openNewTab:"在新标签页中打开",otherCalendar:"Apple / 其他日历",downloadIcs:"下载 .ics 文件",eventPrivacy:"只会添加此事件的标题、日期、行动和原文措辞，不会添加整份文件。" };
translations["zh-TW"] = { ...translations["zh-TW"],buildForGood:"公益專案",mainNavigation:"主導覽",interfaceLanguage:"介面語言",chooseDocument:"選擇 PDF、DOCX 或 TXT 文件",removeDocument:"移除文件",aiProvider:"AI 服務商",configureProvider:"請先在設定中配置服務商",pastedTextName:"貼上的文字",pasteFirst:"請先貼上一些文件文字。",noProvider:"尚未設定 AI 服務商。請前往設定新增。",readingDocument:"正在讀取文件",readyToExplain:"已準備好說明",documentReadError:"無法讀取此文件。",lookingForDates:"正在尋找重要日期",simplifyingDocument:"正在簡化文件",translatingDocument:"正在翻譯文件",explanationReady:"說明已完成",explanationError:"無法說明此文件。",formsDescription:"表格、文件與說明會",incomeDescription:"收入證明要求",threeDeadlines:"3 個截止期限",relativeDeadline:"相對期限",timezoneNotStated:"未註明時區",confidence:"可信度",dateUnavailable:"日期無法使用",closeCalendar:"關閉行事曆選項",addToCalendarTitle:"加入行事曆",allDayEvent:"全天事件",verifyTimezone:"請核對本地時區",remindMe:"提醒我",onTheDay:"當天",oneDayBefore:"提前 1 天",threeDaysBefore:"提前 3 天",oneWeekBefore:"提前 1 週",noReminder:"不提醒",openNewTab:"在新分頁開啟",otherCalendar:"Apple / 其他行事曆",downloadIcs:"下載 .ics 文件",eventPrivacy:"只會加入此事件的標題、日期、行動與原文措辭，不會加入整份文件。" };
translations.fr = { ...translations.fr,buildForGood:"Projet solidaire",mainNavigation:"Navigation principale",interfaceLanguage:"Langue de l’interface",chooseDocument:"Choisir un document PDF, DOCX ou TXT",removeDocument:"Retirer le document",aiProvider:"Fournisseur d’IA",configureProvider:"Configurez un fournisseur dans les réglages",pastedTextName:"Texte collé",pasteFirst:"Collez d’abord le texte d’un document.",noProvider:"Aucun fournisseur d’IA n’est configuré. Ouvrez les réglages pour en ajouter un.",readingDocument:"Lecture du document",readyToExplain:"Prêt à expliquer",documentReadError:"Ce document n’a pas pu être lu.",lookingForDates:"Recherche des dates importantes",simplifyingDocument:"Simplification du document",translatingDocument:"Traduction du document",explanationReady:"Explication prête",explanationError:"Le document n’a pas pu être expliqué.",formsDescription:"Formulaires, documents et orientation",incomeDescription:"Demande de justificatif de revenus",threeDeadlines:"3 échéances",relativeDeadline:"délai relatif",timezoneNotStated:"fuseau horaire non indiqué",confidence:"confiance",dateUnavailable:"Date indisponible",closeCalendar:"Fermer les options du calendrier",addToCalendarTitle:"AJOUTER AU CALENDRIER",allDayEvent:"Toute la journée",verifyTimezone:"vérifiez le fuseau horaire local",remindMe:"Me rappeler",onTheDay:"Le jour même",oneDayBefore:"1 jour avant",threeDaysBefore:"3 jours avant",oneWeekBefore:"1 semaine avant",noReminder:"Aucun rappel",openNewTab:"Ouvrir dans un nouvel onglet",otherCalendar:"Apple / autre calendrier",downloadIcs:"Télécharger un fichier .ics",eventPrivacy:"Seuls le titre, la date, l’action et le texte source de cet événement sont ajoutés, pas le document entier." };
translations.de = { ...translations.de,buildForGood:"Gemeinnütziges Projekt",mainNavigation:"Hauptnavigation",interfaceLanguage:"Oberflächensprache",chooseDocument:"PDF-, DOCX- oder TXT-Dokument auswählen",removeDocument:"Dokument entfernen",aiProvider:"KI-Anbieter",configureProvider:"Anbieter in den Einstellungen konfigurieren",pastedTextName:"Eingefügter Text",pasteFirst:"Füge zuerst Dokumenttext ein.",noProvider:"Kein KI-Anbieter ist eingerichtet. Öffne die Einstellungen, um einen hinzuzufügen.",readingDocument:"Dokument wird gelesen",readyToExplain:"Bereit zur Erklärung",documentReadError:"Dieses Dokument konnte nicht gelesen werden.",lookingForDates:"Wichtige Daten werden gesucht",simplifyingDocument:"Dokument wird vereinfacht",translatingDocument:"Dokument wird übersetzt",explanationReady:"Erklärung ist fertig",explanationError:"Das Dokument konnte nicht erklärt werden.",formsDescription:"Formulare, Dokumente und Orientierung",incomeDescription:"Anforderung eines Einkommensnachweises",threeDeadlines:"3 Fristen",relativeDeadline:"relative Frist",timezoneNotStated:"Zeitzone nicht angegeben",confidence:"Sicherheit",dateUnavailable:"Datum nicht verfügbar",closeCalendar:"Kalenderoptionen schließen",addToCalendarTitle:"ZUM KALENDER HINZUFÜGEN",allDayEvent:"Ganztägiger Termin",verifyTimezone:"lokale Zeitzone prüfen",remindMe:"Erinnern",onTheDay:"Am selben Tag",oneDayBefore:"1 Tag vorher",threeDaysBefore:"3 Tage vorher",oneWeekBefore:"1 Woche vorher",noReminder:"Keine Erinnerung",openNewTab:"In neuem Tab öffnen",otherCalendar:"Apple / anderer Kalender",downloadIcs:".ics-Datei herunterladen",eventPrivacy:"Nur Titel, Datum, Aktion und Quelltext dieses Termins werden hinzugefügt, nicht das gesamte Dokument." };
translations.ko = { ...translations.ko,buildForGood:"공익 프로젝트",mainNavigation:"주요 탐색",interfaceLanguage:"인터페이스 언어",chooseDocument:"PDF, DOCX 또는 TXT 문서 선택",removeDocument:"문서 제거",aiProvider:"AI 제공업체",configureProvider:"설정에서 제공업체를 구성하세요",pastedTextName:"붙여넣은 텍스트",pasteFirst:"먼저 문서 텍스트를 붙여넣으세요.",noProvider:"구성된 AI 제공업체가 없습니다. 설정에서 추가하세요.",readingDocument:"문서 읽는 중",readyToExplain:"설명 준비 완료",documentReadError:"이 문서를 읽을 수 없습니다.",lookingForDates:"중요한 날짜 찾는 중",simplifyingDocument:"문서 단순화 중",translatingDocument:"문서 번역 중",explanationReady:"설명 준비 완료",explanationError:"문서를 설명할 수 없습니다.",formsDescription:"양식, 문서 및 오리엔테이션",incomeDescription:"소득 확인 요청",threeDeadlines:"마감일 3개",relativeDeadline:"상대적 마감일",timezoneNotStated:"시간대가 명시되지 않음",confidence:"신뢰도",dateUnavailable:"날짜를 사용할 수 없음",closeCalendar:"달력 옵션 닫기",addToCalendarTitle:"달력에 추가",allDayEvent:"종일 일정",verifyTimezone:"현지 시간대 확인",remindMe:"알림",onTheDay:"당일",oneDayBefore:"1일 전",threeDaysBefore:"3일 전",oneWeekBefore:"1주 전",noReminder:"알림 없음",openNewTab:"새 탭에서 열기",otherCalendar:"Apple / 기타 달력",downloadIcs:".ics 파일 다운로드",eventPrivacy:"전체 문서가 아니라 이 일정의 제목, 날짜, 조치 및 원문 문구만 추가됩니다." };

translations["zh-CN"] = { ...translations["zh-CN"],backToDemo:"返回演示",settingsUnavailable:"公开演示站不提供设置功能",settingsUnavailableCopy:"请克隆并自行托管 Comprendoc，以配置自己的 AI 服务商。",backToComprendoc:"返回 Comprendoc",selfHostedConfiguration:"自托管配置",providerVault:"AI 服务商密钥库",providerVaultCopy:"加密保存多个服务商密钥，并选择由哪个模型处理每份文件。",encryptedAtRest:"使用 AES-256-GCM 加密",encryptedAtRestCopy:"密钥保存后不会再传回此页面。数据库只存储密文，主密钥保留在服务器环境中。",unlockProviderSettings:"解锁服务商设置",unlockProviderCopy:"请输入 COMPRENDOC_ADMIN_TOKEN 中配置的管理员令牌。令牌只保留在本次浏览器会话中。",administratorToken:"管理员令牌",unlockSettings:"解锁设置",loadSettingsError:"无法加载服务商设置。",enterProviderKey:"请输入新的 {provider} API 密钥。",saveProviderError:"无法保存此服务商。",providerSaved:"已保存 {provider}。密钥已加密，无法显示。",removeProviderConfirm:"移除已保存的 {provider} 密钥？此操作无法撤销。",removeProviderError:"无法移除此服务商。",providerRemoved:"已移除 {provider}。",configuredCount:"已配置 {configured}/{total}",replaceKeyWarning:"保存新密钥会永久替换旧密钥。",lockSettings:"锁定设置",configured:"已配置",defaultProvider:"默认",notConfigured:"未配置",providerDocumentation:"{provider} 文档",endpoint:"接口地址",modelId:"模型 ID",newApiKey:"新 API 密钥（替换已保存的密钥）",apiKeyLabel:"API 密钥",savedKeyHidden:"已保存的密钥已隐藏",pasteKey:"粘贴密钥",makeDefault:"设为默认服务商",replaceKey:"替换密钥",saveProvider:"保存服务商",removeProvider:"移除" };
translations["zh-TW"] = { ...translations["zh-TW"],backToDemo:"返回示範",settingsUnavailable:"公開示範站不提供設定功能",settingsUnavailableCopy:"請複製並自行架設 Comprendoc，以設定自己的 AI 服務商。",backToComprendoc:"返回 Comprendoc",selfHostedConfiguration:"自架設定",providerVault:"AI 服務商金鑰庫",providerVaultCopy:"加密儲存多個服務商金鑰，並選擇由哪個模型處理每份文件。",encryptedAtRest:"使用 AES-256-GCM 加密",encryptedAtRestCopy:"金鑰儲存後不會再傳回此頁面。資料庫只保存密文，主金鑰保留在伺服器環境中。",unlockProviderSettings:"解鎖服務商設定",unlockProviderCopy:"請輸入 COMPRENDOC_ADMIN_TOKEN 中設定的管理員權杖。權杖只保留在本次瀏覽器工作階段。",administratorToken:"管理員權杖",unlockSettings:"解鎖設定",loadSettingsError:"無法載入服務商設定。",enterProviderKey:"請輸入新的 {provider} API 金鑰。",saveProviderError:"無法儲存此服務商。",providerSaved:"已儲存 {provider}。金鑰已加密，無法顯示。",removeProviderConfirm:"移除已儲存的 {provider} 金鑰？此操作無法復原。",removeProviderError:"無法移除此服務商。",providerRemoved:"已移除 {provider}。",configuredCount:"已設定 {configured}/{total}",replaceKeyWarning:"儲存新金鑰會永久取代舊金鑰。",lockSettings:"鎖定設定",configured:"已設定",defaultProvider:"預設",notConfigured:"未設定",providerDocumentation:"{provider} 文件",endpoint:"端點",modelId:"模型 ID",newApiKey:"新 API 金鑰（取代已儲存的金鑰）",apiKeyLabel:"API 金鑰",savedKeyHidden:"已儲存的金鑰已隱藏",pasteKey:"貼上金鑰",makeDefault:"設為預設服務商",replaceKey:"取代金鑰",saveProvider:"儲存服務商",removeProvider:"移除" };
translations.fr = { ...translations.fr,backToDemo:"Retour à la démo",settingsUnavailable:"Les réglages ne sont pas disponibles dans la démo publique",settingsUnavailableCopy:"Clonez et auto-hébergez Comprendoc pour configurer vos propres fournisseurs.",backToComprendoc:"Retour à Comprendoc",selfHostedConfiguration:"CONFIGURATION AUTO-HÉBERGÉE",providerVault:"Coffre des fournisseurs d’IA",providerVaultCopy:"Stockez plusieurs clés chiffrées et choisissez le modèle qui traite chaque document.",encryptedAtRest:"Chiffrement AES-256-GCM",encryptedAtRestCopy:"Les clés ne sont jamais renvoyées à cette page. La base contient le texte chiffré et la clé principale reste dans l’environnement serveur.",unlockProviderSettings:"Déverrouiller les réglages",unlockProviderCopy:"Saisissez le jeton administrateur défini dans COMPRENDOC_ADMIN_TOKEN. Il reste uniquement dans cette session du navigateur.",administratorToken:"Jeton administrateur",unlockSettings:"Déverrouiller",loadSettingsError:"Impossible de charger les réglages des fournisseurs.",enterProviderKey:"Saisissez une nouvelle clé API {provider}.",saveProviderError:"Impossible d’enregistrer ce fournisseur.",providerSaved:"{provider} a été enregistré. La clé est chiffrée et ne peut pas être affichée.",removeProviderConfirm:"Supprimer la clé {provider} enregistrée ? Cette action est irréversible.",removeProviderError:"Impossible de supprimer ce fournisseur.",providerRemoved:"{provider} a été supprimé.",configuredCount:"{configured} sur {total} configurés",replaceKeyWarning:"L’enregistrement d’une nouvelle clé remplace définitivement l’ancienne.",lockSettings:"Verrouiller",configured:"Configuré",defaultProvider:"par défaut",notConfigured:"Non configuré",providerDocumentation:"Documentation {provider}",endpoint:"Point d’accès",modelId:"Identifiant du modèle",newApiKey:"Nouvelle clé API (remplace la clé enregistrée)",apiKeyLabel:"Clé API",savedKeyHidden:"La clé enregistrée est masquée",pasteKey:"Coller la clé",makeDefault:"Définir comme fournisseur par défaut",replaceKey:"Remplacer la clé",saveProvider:"Enregistrer le fournisseur",removeProvider:"Supprimer" };
translations.de = { ...translations.de,backToDemo:"Zurück zur Demo",settingsUnavailable:"Einstellungen sind in der öffentlichen Demo nicht verfügbar",settingsUnavailableCopy:"Klone Comprendoc und hoste es selbst, um eigene Anbieter einzurichten.",backToComprendoc:"Zurück zu Comprendoc",selfHostedConfiguration:"SELF-HOSTING-KONFIGURATION",providerVault:"Tresor für KI-Anbieter",providerVaultCopy:"Speichere mehrere Anbieterschlüssel verschlüsselt und wähle das Modell für jedes Dokument.",encryptedAtRest:"AES-256-GCM-verschlüsselt",encryptedAtRestCopy:"Schlüssel werden nach dem Speichern nie an diese Seite zurückgegeben. Die Datenbank enthält nur Geheimtext; der Hauptschlüssel bleibt in der Serverumgebung.",unlockProviderSettings:"Anbietereinstellungen entsperren",unlockProviderCopy:"Gib das in COMPRENDOC_ADMIN_TOKEN festgelegte Administratortoken ein. Es bleibt nur in dieser Browsersitzung.",administratorToken:"Administratortoken",unlockSettings:"Einstellungen entsperren",loadSettingsError:"Anbietereinstellungen konnten nicht geladen werden.",enterProviderKey:"Gib einen neuen API-Schlüssel für {provider} ein.",saveProviderError:"Dieser Anbieter konnte nicht gespeichert werden.",providerSaved:"{provider} wurde gespeichert. Der Schlüssel ist verschlüsselt und kann nicht angezeigt werden.",removeProviderConfirm:"Gespeicherten Schlüssel für {provider} entfernen? Dies kann nicht rückgängig gemacht werden.",removeProviderError:"Dieser Anbieter konnte nicht entfernt werden.",providerRemoved:"{provider} wurde entfernt.",configuredCount:"{configured} von {total} eingerichtet",replaceKeyWarning:"Ein neuer Schlüssel ersetzt den bisherigen dauerhaft.",lockSettings:"Einstellungen sperren",configured:"Eingerichtet",defaultProvider:"Standard",notConfigured:"Nicht eingerichtet",providerDocumentation:"Dokumentation zu {provider}",endpoint:"Endpunkt",modelId:"Modell-ID",newApiKey:"Neuer API-Schlüssel (ersetzt den gespeicherten)",apiKeyLabel:"API-Schlüssel",savedKeyHidden:"Gespeicherter Schlüssel ist ausgeblendet",pasteKey:"Schlüssel einfügen",makeDefault:"Als Standardanbieter festlegen",replaceKey:"Schlüssel ersetzen",saveProvider:"Anbieter speichern",removeProvider:"Entfernen" };
translations.ko = { ...translations.ko,backToDemo:"데모로 돌아가기",settingsUnavailable:"공개 데모에서는 설정을 사용할 수 없습니다",settingsUnavailableCopy:"Comprendoc을 복제하고 직접 호스팅하여 제공업체를 구성하세요.",backToComprendoc:"Comprendoc으로 돌아가기",selfHostedConfiguration:"셀프 호스팅 구성",providerVault:"AI 제공업체 보관함",providerVaultCopy:"여러 제공업체 키를 암호화하여 저장하고 각 문서를 처리할 모델을 선택하세요.",encryptedAtRest:"AES-256-GCM 암호화",encryptedAtRestCopy:"저장된 키는 이 페이지로 다시 전송되지 않습니다. 데이터베이스에는 암호문만 있고 마스터 키는 서버 환경에 남습니다.",unlockProviderSettings:"제공업체 설정 잠금 해제",unlockProviderCopy:"COMPRENDOC_ADMIN_TOKEN에 설정된 관리자 토큰을 입력하세요. 이 브라우저 세션에만 유지됩니다.",administratorToken:"관리자 토큰",unlockSettings:"설정 잠금 해제",loadSettingsError:"제공업체 설정을 불러올 수 없습니다.",enterProviderKey:"새 {provider} API 키를 입력하세요.",saveProviderError:"이 제공업체를 저장할 수 없습니다.",providerSaved:"{provider}이(가) 저장되었습니다. 키는 암호화되어 표시할 수 없습니다.",removeProviderConfirm:"저장된 {provider} 키를 제거할까요? 되돌릴 수 없습니다.",removeProviderError:"이 제공업체를 제거할 수 없습니다.",providerRemoved:"{provider}이(가) 제거되었습니다.",configuredCount:"{total}개 중 {configured}개 구성됨",replaceKeyWarning:"새 키를 저장하면 이전 키가 영구적으로 교체됩니다.",lockSettings:"설정 잠금",configured:"구성됨",defaultProvider:"기본",notConfigured:"구성되지 않음",providerDocumentation:"{provider} 문서",endpoint:"엔드포인트",modelId:"모델 ID",newApiKey:"새 API 키(저장된 키 교체)",apiKeyLabel:"API 키",savedKeyHidden:"저장된 키는 숨겨져 있습니다",pasteKey:"키 붙여넣기",makeDefault:"기본 제공업체로 설정",replaceKey:"키 교체",saveProvider:"제공업체 저장",removeProvider:"제거" };

translations["zh-CN"] = { ...translations["zh-CN"],demoStudentTitle:"国际学生入学步骤",demoStudentSummary:"提交入学表格、支付押金、提供所需文件并参加说明会。",demoStudentPlain:"这份合成通知包含三个重要日期。先完成表格，再提交文件，最后参加说明会。",demoApartmentTitle:"收入证明请求",demoApartmentSummary:"请在收到通知后的 10 个工作日内交回收入证明表格。",demoApartmentPlain:"确切截止日期取决于收到通知的日期。请先确认该日期，再安排回复。" };
translations["zh-TW"] = { ...translations["zh-TW"],demoStudentTitle:"國際學生入學步驟",demoStudentSummary:"提交入學表格、支付訂金、提供所需文件並參加入學說明會。",demoStudentPlain:"這份合成通知包含三個重要日期。先完成表格，再提交文件，最後參加入學說明會。",demoApartmentTitle:"收入證明要求",demoApartmentSummary:"請在收到通知後的 10 個工作天內交回收入證明表格。",demoApartmentPlain:"確切截止日期取決於收到通知的日期。請先確認該日期，再安排回覆。" };
translations.fr = { ...translations.fr,demoStudentTitle:"Étapes d’inscription des étudiants internationaux",demoStudentSummary:"Envoyez le formulaire d’inscription, payez l’acompte, fournissez les documents demandés et assistez à l’orientation.",demoStudentPlain:"Cet avis fictif contient trois dates importantes. Remplissez d’abord le formulaire, envoyez ensuite les documents, puis assistez à l’orientation.",demoApartmentTitle:"Demande de justificatif de revenus",demoApartmentSummary:"Renvoyez le formulaire de vérification des revenus dans les 10 jours ouvrables suivant la réception de l’avis.",demoApartmentPlain:"La date exacte dépend du jour de réception de l’avis. Vérifiez cette date avant de planifier votre réponse." };
translations.de = { ...translations.de,demoStudentTitle:"Schritte zur Einschreibung internationaler Studierender",demoStudentSummary:"Reiche das Einschreibeformular ein, zahle die Kaution, sende die angeforderten Unterlagen und nimm an der Orientierung teil.",demoStudentPlain:"Dieser synthetische Bescheid enthält drei wichtige Termine. Fülle zuerst das Formular aus, sende dann die Unterlagen und nimm zuletzt an der Orientierung teil.",demoApartmentTitle:"Anforderung eines Einkommensnachweises",demoApartmentSummary:"Sende das Einkommensnachweisformular innerhalb von 10 Werktagen nach Erhalt des Bescheids zurück.",demoApartmentPlain:"Die genaue Frist hängt vom Empfangsdatum ab. Prüfe dieses Datum, bevor du deine Antwort planst." };
translations.ko = { ...translations.ko,demoStudentTitle:"유학생 등록 단계",demoStudentSummary:"등록 양식을 제출하고 예치금을 납부한 뒤 요청된 문서를 제공하고 오리엔테이션에 참석하세요.",demoStudentPlain:"이 합성 안내문에는 세 가지 중요한 날짜가 있습니다. 먼저 양식을 작성하고 문서를 제출한 뒤 마지막으로 오리엔테이션에 참석하세요.",demoApartmentTitle:"소득 확인 요청",demoApartmentSummary:"안내문을 받은 날부터 영업일 기준 10일 이내에 소득 확인 양식을 제출하세요.",demoApartmentPlain:"정확한 마감일은 안내문을 받은 날짜에 따라 달라집니다. 답변 계획 전에 해당 날짜를 확인하세요." };

translations["zh-CN"] = { ...translations["zh-CN"],library:"文档库",saveDocument:"保存文档",savingDocument:"正在保存…",saved:"已保存",documentSaved:"已将此处理后的文档保存到加密文档库。",saveDocumentError:"无法保存此文档。",unlockLibraryFirst:"请先使用管理员令牌解锁文档库，然后再保存或打开文档。",loadingDocuments:"正在加载已保存的文档",loadDocumentError:"无法打开此已保存文档。",savedDocuments:"已保存的文档",yourLibrary:"你的文档库",libraryCopy:"无需再次运行 AI 分析，即可打开之前处理过的文档。文档内容会加密存储。",unlockLibrary:"解锁文档库",unlockLibraryCopy:"使用与提供商设置相同的管理员令牌。令牌只保留在本次浏览器会话中。",unlockLibraryButton:"解锁文档库",lockLibrary:"锁定文档库",savedCount:"已保存 {count} 份文档",loadDocumentsError:"无法加载已保存的文档。",noSavedDocuments:"尚未保存文档",noSavedDocumentsCopy:"处理文档后，在结果页面选择“保存文档”。",addDocument:"处理文档",deadlineCount:"{count} 个截止日期",openDocument:"打开",deleteDocument:"删除",deleteDocumentLabel:"删除 {title}",deleteDocumentConfirm:"删除“{title}”？此操作无法撤销。",deleteDocumentError:"无法删除此文档。",documentDeleted:"文档已删除。",libraryUnavailable:"公开演示中不提供文档库",libraryUnavailableCopy:"请自行托管 Comprendoc，以安全保存处理后的文档。",selfHostedFooterMeta:"为公益而建 · 无需账户 · 加密文档库" };
translations["zh-TW"] = { ...translations["zh-TW"],library:"文件庫",saveDocument:"儲存文件",savingDocument:"正在儲存…",saved:"已儲存",documentSaved:"已將此處理後的文件儲存至加密文件庫。",saveDocumentError:"無法儲存此文件。",unlockLibraryFirst:"請先使用管理員權杖解鎖文件庫，再儲存或開啟文件。",loadingDocuments:"正在載入已儲存的文件",loadDocumentError:"無法開啟此已儲存文件。",savedDocuments:"已儲存的文件",yourLibrary:"你的文件庫",libraryCopy:"無需再次執行 AI 分析，即可開啟先前處理過的文件。文件內容會加密儲存。",unlockLibrary:"解鎖文件庫",unlockLibraryCopy:"使用與供應商設定相同的管理員權杖。權杖只保留於本次瀏覽器工作階段。",unlockLibraryButton:"解鎖文件庫",lockLibrary:"鎖定文件庫",savedCount:"已儲存 {count} 份文件",loadDocumentsError:"無法載入已儲存的文件。",noSavedDocuments:"尚未儲存文件",noSavedDocumentsCopy:"處理文件後，在結果頁面選擇「儲存文件」。",addDocument:"處理文件",deadlineCount:"{count} 個截止期限",openDocument:"開啟",deleteDocument:"刪除",deleteDocumentLabel:"刪除 {title}",deleteDocumentConfirm:"刪除「{title}」？此操作無法復原。",deleteDocumentError:"無法刪除此文件。",documentDeleted:"文件已刪除。",libraryUnavailable:"公開示範中不提供文件庫",libraryUnavailableCopy:"請自行託管 Comprendoc，以安全儲存處理後的文件。",selfHostedFooterMeta:"為公益而建 · 無需帳號 · 加密文件庫" };
translations.fr = { ...translations.fr,library:"Bibliothèque",saveDocument:"Enregistrer",savingDocument:"Enregistrement…",saved:"Enregistré",documentSaved:"Ce document traité est enregistré dans votre bibliothèque chiffrée.",saveDocumentError:"Ce document n’a pas pu être enregistré.",unlockLibraryFirst:"Déverrouillez la bibliothèque avec le jeton administrateur avant d’enregistrer ou d’ouvrir des documents.",loadingDocuments:"Chargement du document enregistré",loadDocumentError:"Ce document enregistré n’a pas pu être ouvert.",savedDocuments:"DOCUMENTS ENREGISTRÉS",yourLibrary:"Votre bibliothèque de documents",libraryCopy:"Ouvrez vos documents déjà traités sans relancer l’analyse IA. Leur contenu est chiffré au repos.",unlockLibrary:"Déverrouiller la bibliothèque",unlockLibraryCopy:"Utilisez le même jeton administrateur que pour les fournisseurs. Il reste uniquement dans cette session.",unlockLibraryButton:"Déverrouiller",lockLibrary:"Verrouiller",savedCount:"{count} documents enregistrés",loadDocumentsError:"Impossible de charger les documents enregistrés.",noSavedDocuments:"Aucun document enregistré",noSavedDocumentsCopy:"Traitez un document, puis sélectionnez Enregistrer sur la page de résultat.",addDocument:"Traiter un document",deadlineCount:"{count} échéances",openDocument:"Ouvrir",deleteDocument:"Supprimer",deleteDocumentLabel:"Supprimer {title}",deleteDocumentConfirm:"Supprimer « {title} » ? Cette action est irréversible.",deleteDocumentError:"Ce document n’a pas pu être supprimé.",documentDeleted:"Document supprimé.",libraryUnavailable:"La bibliothèque est indisponible dans la démo publique",libraryUnavailableCopy:"Auto-hébergez Comprendoc pour enregistrer vos documents traités en toute sécurité.",selfHostedFooterMeta:"Conçu pour le bien · Sans compte · Bibliothèque chiffrée" };
translations.de = { ...translations.de,library:"Bibliothek",saveDocument:"Dokument speichern",savingDocument:"Wird gespeichert…",saved:"Gespeichert",documentSaved:"Dieses verarbeitete Dokument wurde in deiner verschlüsselten Bibliothek gespeichert.",saveDocumentError:"Dieses Dokument konnte nicht gespeichert werden.",unlockLibraryFirst:"Entsperre die Bibliothek mit dem Administratortoken, bevor du Dokumente speicherst oder öffnest.",loadingDocuments:"Gespeichertes Dokument wird geladen",loadDocumentError:"Dieses gespeicherte Dokument konnte nicht geöffnet werden.",savedDocuments:"GESPEICHERTE DOKUMENTE",yourLibrary:"Deine Dokumentbibliothek",libraryCopy:"Öffne bereits verarbeitete Dokumente, ohne die KI-Analyse erneut auszuführen. Die Inhalte sind verschlüsselt gespeichert.",unlockLibrary:"Bibliothek entsperren",unlockLibraryCopy:"Verwende dasselbe Administratortoken wie in den Anbietereinstellungen. Es bleibt nur in dieser Browsersitzung.",unlockLibraryButton:"Bibliothek entsperren",lockLibrary:"Bibliothek sperren",savedCount:"{count} gespeicherte Dokumente",loadDocumentsError:"Gespeicherte Dokumente konnten nicht geladen werden.",noSavedDocuments:"Noch nichts gespeichert",noSavedDocumentsCopy:"Verarbeite ein Dokument und wähle anschließend auf der Ergebnisseite „Dokument speichern“.",addDocument:"Dokument verarbeiten",deadlineCount:"{count} Fristen",openDocument:"Öffnen",deleteDocument:"Löschen",deleteDocumentLabel:"{title} löschen",deleteDocumentConfirm:"„{title}“ löschen? Dies kann nicht rückgängig gemacht werden.",deleteDocumentError:"Dieses Dokument konnte nicht gelöscht werden.",documentDeleted:"Dokument gelöscht.",libraryUnavailable:"Die Bibliothek ist in der öffentlichen Demo nicht verfügbar",libraryUnavailableCopy:"Hoste Comprendoc selbst, um verarbeitete Dokumente sicher zu speichern.",selfHostedFooterMeta:"Für das Gemeinwohl · Ohne Konten · Verschlüsselte Bibliothek" };
translations.ko = { ...translations.ko,library:"문서함",saveDocument:"문서 저장",savingDocument:"저장 중…",saved:"저장됨",documentSaved:"처리된 문서가 암호화된 문서함에 저장되었습니다.",saveDocumentError:"이 문서를 저장할 수 없습니다.",unlockLibraryFirst:"문서를 저장하거나 열기 전에 관리자 토큰으로 문서함을 잠금 해제하세요.",loadingDocuments:"저장된 문서 불러오는 중",loadDocumentError:"이 저장된 문서를 열 수 없습니다.",savedDocuments:"저장된 문서",yourLibrary:"내 문서함",libraryCopy:"AI 분석을 다시 실행하지 않고 이전에 처리한 문서를 열 수 있습니다. 문서 내용은 암호화되어 저장됩니다.",unlockLibrary:"문서함 잠금 해제",unlockLibraryCopy:"제공업체 설정과 동일한 관리자 토큰을 사용하세요. 이 브라우저 세션에만 유지됩니다.",unlockLibraryButton:"문서함 잠금 해제",lockLibrary:"문서함 잠금",savedCount:"저장된 문서 {count}개",loadDocumentsError:"저장된 문서를 불러올 수 없습니다.",noSavedDocuments:"아직 저장된 문서가 없습니다",noSavedDocumentsCopy:"문서를 처리한 뒤 결과 페이지에서 문서 저장을 선택하세요.",addDocument:"문서 처리",deadlineCount:"마감일 {count}개",openDocument:"열기",deleteDocument:"삭제",deleteDocumentLabel:"{title} 삭제",deleteDocumentConfirm:"‘{title}’을(를) 삭제할까요? 되돌릴 수 없습니다.",deleteDocumentError:"이 문서를 삭제할 수 없습니다.",documentDeleted:"문서가 삭제되었습니다.",libraryUnavailable:"공개 데모에서는 문서함을 사용할 수 없습니다",libraryUnavailableCopy:"Comprendoc을 직접 호스팅하여 처리된 문서를 안전하게 저장하세요.",selfHostedFooterMeta:"공익을 위해 제작 · 계정 없음 · 암호화된 문서함" };

export function messages(locale: Locale): Messages {
  return { ...en, ...(translations[locale] || {}) };
}

export function missingTranslationKeys(locale: Locale): string[] {
  if (locale === "en") return [];
  const localeMessages = translations[locale] || {};
  return Object.keys(en).filter((key) => !(key in localeMessages));
}

export function providerDisclosure(message: string, providerName: string): string {
  return message.replace("{provider}", providerName).replace("OpenAI", providerName);
}

export function formatMessage(message: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), message);
}

export function languageLabel(locale: Locale, languageCode: string): string {
  return new Intl.DisplayNames([locale], { type: "language" }).of(languageCode) || languageCode;
}

export function detectLocale(languageTags: readonly string[]): Locale {
  for (const tag of languageTags) {
    const normalized = tag.toLowerCase().replaceAll("_", "-");
    const exact = interfaceLanguages.find((item) => item.code.toLowerCase() === normalized);
    if (exact) return exact.code;
    if (normalized.startsWith("zh-") && /-(tw|hk|mo|hant)(-|$)/.test(normalized)) return "zh-TW";
    if (normalized.startsWith("zh-") && /-(cn|sg|hans)(-|$)/.test(normalized)) return "zh-CN";
    const base = normalized.split("-")[0];
    const match = interfaceLanguages.find((item) => item.code.toLowerCase().split("-")[0] === base);
    if (match) return match.code;
  }
  return "en";
}
