export const uiLanguages = [
  { code: "en", label: "English", analysis: "English", dir: "ltr" },
  { code: "zh-CN", label: "简体中文", analysis: "Simplified Chinese", dir: "ltr" },
  { code: "zh-TW", label: "繁體中文", analysis: "Traditional Chinese", dir: "ltr" },
  { code: "es", label: "Español", analysis: "Spanish", dir: "ltr" },
  { code: "fr", label: "Français", analysis: "French", dir: "ltr" },
  { code: "de", label: "Deutsch", analysis: "German", dir: "ltr" },
  { code: "ar", label: "العربية", analysis: "Arabic", dir: "rtl" },
  { code: "pt", label: "Português", analysis: "Portuguese", dir: "ltr" },
  { code: "hi", label: "हिन्दी", analysis: "Hindi", dir: "ltr" },
  { code: "ru", label: "Русский", analysis: "Russian", dir: "ltr" },
  { code: "vi", label: "Tiếng Việt", analysis: "Vietnamese", dir: "ltr" },
  { code: "ja", label: "日本語", analysis: "Japanese", dir: "ltr" },
  { code: "ko", label: "한국어", analysis: "Korean", dir: "ltr" },
] as const;

export type Locale = (typeof uiLanguages)[number]["code"];

const en = {
  privacy: "Privacy", how: "How it works", demo: "Demo", settings: "Settings",
  tagline: "Comprehend the docs. Act on what matters.", hero1: "Understand the paperwork.", hero2: "Know what to do next.",
  heroCopy: "Comprendoc turns complicated documents into clear explanations in your language — and helps you keep track of what matters.",
  demoTitle: "Explore the Comprendoc demo", demoCopy: "This public site uses synthetic examples only. It never accepts documents or makes paid AI requests.", demoButton: "View a demo document",
  drop: "Drop a document here", formats: "PDF, DOCX or TXT · up to 25 MB", choose: "Choose a file", or: "or", paste: "Paste text instead", closePaste: "Close text box",
  pasteLabel: "Paste your document text", pastePlaceholder: "Paste the letter, notice, or form text here…", useText: "Use this text",
  filePrivate: "Your file stays in your browser.", filePrivate2: "Only extracted text is sent for AI analysis.",
  tryExample: "TRY AN EXAMPLE", seeAction: "See Comprendoc in action", synthetic: "Synthetic documents. No personal information.",
  howLabel: "HOW IT WORKS", howTitle: "From red tape to a clear next step", step1: "Add your document", step1Copy: "Upload or paste. Your original file never leaves your browser.", step2: "Choose your language", step2Copy: "Get a natural explanation at the level that works for you.", step3: "Act with confidence", step3Copy: "See deadlines, verify sources, and add dates to your calendar.",
  startOver: "Start over", ready: "DOCUMENT READY", explainHow: "How should we explain it?", extracted: "Your document text was extracted locally. Choose what feels most comfortable.",
  page: "page", pages: "pages", characters: "characters", ocrUsed: "OCR used", textExtracted: "text extracted", ocrWarning: "Some text may have been read incorrectly. Double-check names, dates, amounts, and deadlines against the original.",
  explanationLanguage: "Explanation language", explanationLevel: "Explanation level", simple: "Simple", standard: "Standard", detailed: "Detailed", simpleHint: "Short & clear", standardHint: "Balanced", detailedHint: "More context",
  readyWhen: "Ready when you are.", disclosure: "Extracted document text—not the original file—will be sent to {provider} for analysis.", explain: "Explain this document",
  localWork: "COMPRENDOC IS WORKING LOCALLY", preparing: "Preparing your document", read: "Read document", extract: "Extract text", explainClearly: "Explain clearly", originalPrivate: "Your original file is not uploaded or stored.",
  newDocument: "New document", linked: "Key details are linked to the original text", extraLook: "Take an extra look", whatIs: "WHAT IS THIS?", plain: "In plain language", needKnow: "WHAT YOU NEED TO KNOW", important: "The important points", noPoints: "No important points were found.", deadlines: "DEADLINES", noDeadline: "No deadline found", noActionable: "No actionable deadline was found in this document.", needDo: "WHAT YOU NEED TO DO", nextSteps: "Your next steps", noAction: "No action found in this document", dates: "IMPORTANT DATES", otherDates: "Other dates", money: "MONEY / FEES", amounts: "Amounts mentioned", jargon: "JARGON EXPLAINED", simpler: "Words made simpler", doubleCheck: "THINGS TO DOUBLE-CHECK", uncertain: "Comprendoc is not certain about", checkOriginal: "Check the original", checkCopy: "AI can make mistakes. Verify important dates and requirements against your document.", privateDesign: "Private by design", privateCopy: "No account. No document history. Your original file stayed on this device.",
  sourceText: "ORIGINAL DOCUMENT TEXT", exactWording: "Check the exact wording", viewSource: "View source", addCalendar: "Add to calendar", certainty: "CERTAINTY", exactUnknown: "Exact date cannot be calculated yet.", ifMissed: "If missed", dateRadar: "dates to keep on your radar",
  settingsTitle: "Self-hosted settings", settingsCopy: "Use a server key from OPENAI_API_KEY, or enter your own key for this browser session. Session keys are never saved to disk and clear when the browser session ends.", apiKey: "OpenAI API key", apiPlaceholder: "sk-…", saveSession: "Use for this session", clearKey: "Clear session key", keyReady: "A server-side API key is configured.", keySessionReady: "A session API key is ready.", keyMissing: "Add an API key before analyzing a document.", close: "Close",
  footer: "Comprendoc helps you understand documents, but AI can make mistakes. Verify important dates, deadlines, and requirements against the original document.", footerMeta: "Built for good · No accounts · No document storage",
};

type Messages = typeof en;
const translations: Partial<Record<Locale, Partial<Messages>>> = {
  "zh-CN": { privacy:"隐私",how:"使用方法",demo:"演示",settings:"设置",tagline:"读懂文件，把握要事。",hero1:"看懂复杂文件。",hero2:"清楚下一步该做什么。",heroCopy:"Comprendoc 用你的语言把复杂文件变成清晰说明，并帮你记住重要事项。",demoTitle:"体验 Comprendoc 演示",demoCopy:"此公开网站仅使用合成示例，不接收文件，也不会发起付费 AI 请求。",demoButton:"查看演示文件",drop:"将文件拖到这里",formats:"PDF、DOCX 或 TXT · 最大 25 MB",choose:"选择文件",or:"或",paste:"粘贴文本",closePaste:"关闭文本框",pasteLabel:"粘贴文件文本",pastePlaceholder:"在此粘贴信件、通知或表格文本…",useText:"使用此文本",filePrivate:"文件留在浏览器中。",filePrivate2:"仅提取的文本会发送给 AI 分析。",tryExample:"试用示例",seeAction:"查看 Comprendoc 的效果",synthetic:"合成文件，不含个人信息。",howLabel:"使用方法",howTitle:"从繁文缛节到清晰行动",step1:"添加文件",step1Copy:"上传或粘贴，原始文件不会离开浏览器。",step2:"选择语言",step2Copy:"获得适合你的自然、清晰说明。",step3:"安心行动",step3Copy:"查看截止日期、核对来源并添加到日历。",startOver:"重新开始",ready:"文件已准备",explainHow:"希望我们如何说明？",extracted:"文件文本已在本地提取，请选择合适的方式。",explanationLanguage:"说明语言",explanationLevel:"说明详细程度",simple:"简洁",standard:"标准",detailed:"详细",simpleHint:"短而清楚",standardHint:"平衡",detailedHint:"更多背景",readyWhen:"准备好了。",disclosure:"提取的文本（不是原文件）将发送给 {provider} 分析。",explain:"解释此文件",newDocument:"新文件",linked:"关键细节已链接到原文",extraLook:"请特别核对",whatIs:"这是什么？",plain:"简单说明",needKnow:"你需要知道",important:"重点",deadlines:"截止日期",needDo:"你需要做什么",nextSteps:"下一步",checkOriginal:"核对原文",checkCopy:"AI 可能出错，请对照文件核实重要日期和要求。",privateDesign:"隐私优先",settingsTitle:"自托管设置",settingsCopy:"使用 OPENAI_API_KEY 中的服务器密钥，或输入仅供本次浏览器会话使用的密钥。会话密钥不会写入磁盘，关闭会话后即清除。",apiKey:"OpenAI API 密钥",saveSession:"本次会话使用",clearKey:"清除会话密钥",keyReady:"已配置服务器端 API 密钥。",keySessionReady:"会话 API 密钥已就绪。",keyMissing:"分析文件前请添加 API 密钥。",close:"关闭",footer:"Comprendoc 帮你理解文件，但 AI 可能出错。请对照原文核实重要日期、截止时间和要求。",footerMeta:"为公益而建 · 无账户 · 不存储文件" },
  "zh-TW": { privacy:"隱私權",how:"運作方式",demo:"示範",settings:"設定",tagline:"讀懂文件，掌握重點。",hero1:"看懂複雜文件。",hero2:"清楚下一步該做什麼。",heroCopy:"Comprendoc 用你的語言將複雜文件轉化為清楚易懂的說明，並協助你掌握重要事項。",demoTitle:"體驗 Comprendoc 示範",demoCopy:"此公開網站僅使用合成範例，不接收文件，也不會發出付費 AI 請求。",demoButton:"查看示範文件",drop:"將文件拖放到這裡",formats:"PDF、DOCX 或 TXT · 最大 25 MB",choose:"選擇文件",or:"或",paste:"貼上文字",closePaste:"關閉文字方塊",pasteLabel:"貼上文件文字",pastePlaceholder:"在此貼上信件、通知或表格內容…",useText:"使用此文字",filePrivate:"文件只會留在你的瀏覽器中。",filePrivate2:"只有擷取出的文字會傳送給 AI 分析。",tryExample:"試用範例",seeAction:"看看 Comprendoc 如何運作",synthetic:"合成文件，不含個人資料。",howLabel:"運作方式",howTitle:"從繁瑣文件到清楚的下一步",step1:"加入文件",step1Copy:"上傳或貼上；原始文件不會離開瀏覽器。",step2:"選擇語言",step2Copy:"取得符合你需求、自然易懂的說明。",step3:"安心採取行動",step3Copy:"查看期限、核對來源，並將日期加入行事曆。",startOver:"重新開始",ready:"文件已準備完成",explainHow:"希望我們如何說明？",extracted:"文件文字已在本機擷取，請選擇最適合你的方式。",explanationLanguage:"說明語言",explanationLevel:"說明詳細程度",simple:"簡潔",standard:"標準",detailed:"詳細",simpleHint:"簡短清楚",standardHint:"內容均衡",detailedHint:"更多背景",readyWhen:"準備好了。",disclosure:"擷取出的文字（不是原始文件）將傳送給 {provider} 分析。",explain:"解釋這份文件",newDocument:"新文件",linked:"重要細節已連結至原文",extraLook:"請特別留意",whatIs:"這是什麼？",plain:"白話說明",needKnow:"你需要知道",important:"重要重點",deadlines:"截止期限",needDo:"你需要做什麼",nextSteps:"下一步",checkOriginal:"核對原文",checkCopy:"AI 可能出錯，請對照文件核實重要日期與要求。",privateDesign:"隱私優先設計",footer:"Comprendoc 協助你理解文件，但 AI 可能出錯。請對照原文核實重要日期、期限與要求。",footerMeta:"為公益而建 · 無需帳號 · 不儲存文件" },
  es: { privacy:"Privacidad",how:"Cómo funciona",demo:"Demo",settings:"Ajustes",tagline:"Comprende los documentos. Actúa sobre lo importante.",hero1:"Entiende el papeleo.",hero2:"Sabe qué hacer después.",heroCopy:"Comprendoc convierte documentos complicados en explicaciones claras en tu idioma y te ayuda a seguir lo importante.",demoTitle:"Explora la demo de Comprendoc",demoCopy:"Este sitio público solo usa ejemplos sintéticos. No acepta documentos ni realiza solicitudes de IA de pago.",demoButton:"Ver un documento de muestra",drop:"Suelta un documento aquí",choose:"Elegir archivo",or:"o",paste:"Pegar texto",closePaste:"Cerrar texto",filePrivate:"Tu archivo permanece en el navegador.",filePrivate2:"Solo el texto extraído se envía para análisis.",tryExample:"PRUEBA UN EJEMPLO",seeAction:"Mira Comprendoc en acción",synthetic:"Documentos sintéticos. Sin datos personales.",howLabel:"CÓMO FUNCIONA",howTitle:"Del papeleo al siguiente paso claro",step1:"Añade tu documento",step1Copy:"Sube o pega. El archivo original no sale del navegador.",step2:"Elige tu idioma",step2Copy:"Recibe una explicación natural al nivel que prefieras.",step3:"Actúa con confianza",step3Copy:"Ve plazos, verifica fuentes y añade fechas al calendario.",startOver:"Empezar de nuevo",ready:"DOCUMENTO LISTO",explainHow:"¿Cómo debemos explicarlo?",extracted:"El texto se extrajo localmente. Elige lo que te resulte más cómodo.",explanationLanguage:"Idioma de la explicación",explanationLevel:"Nivel de explicación",simple:"Simple",standard:"Estándar",detailed:"Detallado",readyWhen:"Cuando quieras.",disclosure:"El texto extraído—no el archivo original—se enviará a OpenAI.",explain:"Explicar este documento",newDocument:"Nuevo documento",linked:"Los detalles clave enlazan con el texto original",extraLook:"Revísalo con atención",whatIs:"¿QUÉ ES ESTO?",plain:"En lenguaje sencillo",needKnow:"LO QUE DEBES SABER",important:"Los puntos importantes",deadlines:"PLAZOS",needDo:"LO QUE DEBES HACER",nextSteps:"Tus próximos pasos",checkOriginal:"Comprueba el original",checkCopy:"La IA puede equivocarse. Verifica fechas y requisitos en el documento.",privateDesign:"Privado por diseño",settingsTitle:"Ajustes de alojamiento propio",settingsCopy:"Usa la clave del servidor en OPENAI_API_KEY o introduce una clave solo para esta sesión. Nunca se guarda en disco.",apiKey:"Clave API de OpenAI",saveSession:"Usar en esta sesión",clearKey:"Borrar clave de sesión",keyReady:"Hay una clave API configurada en el servidor.",keySessionReady:"La clave de sesión está lista.",keyMissing:"Añade una clave API antes de analizar.",close:"Cerrar",footer:"Comprendoc ayuda a entender documentos, pero la IA puede equivocarse. Verifica fechas, plazos y requisitos con el original.",footerMeta:"Creado para el bien · Sin cuentas · Sin almacenar documentos" },
  fr: { privacy:"Confidentialité",how:"Fonctionnement",demo:"Démo",settings:"Réglages",tagline:"Comprenez les documents. Agissez sur l’essentiel.",hero1:"Comprenez les démarches.",hero2:"Sachez quoi faire ensuite.",heroCopy:"Comprendoc transforme les documents complexes en explications claires dans votre langue et suit l’essentiel.",demoTitle:"Explorez la démo Comprendoc",demoCopy:"Ce site public utilise uniquement des exemples fictifs. Aucun document ni appel IA payant.",demoButton:"Voir un document de démo",drop:"Déposez un document ici",choose:"Choisir un fichier",or:"ou",paste:"Coller du texte",filePrivate:"Votre fichier reste dans le navigateur.",filePrivate2:"Seul le texte extrait est envoyé pour analyse.",tryExample:"ESSAYER UN EXEMPLE",seeAction:"Découvrez Comprendoc",synthetic:"Documents fictifs. Aucune donnée personnelle.",howLabel:"FONCTIONNEMENT",howTitle:"Des formalités à une prochaine étape claire",step1:"Ajoutez votre document",step1Copy:"Importez ou collez. L’original ne quitte jamais le navigateur.",step2:"Choisissez votre langue",step2Copy:"Obtenez une explication naturelle au niveau adapté.",step3:"Agissez en confiance",step3Copy:"Repérez les échéances, vérifiez les sources et ajoutez les dates au calendrier.",startOver:"Recommencer",ready:"DOCUMENT PRÊT",explainHow:"Comment devons-nous l’expliquer ?",extracted:"Le texte a été extrait localement. Choisissez ce qui vous convient.",explanationLanguage:"Langue de l’explication",explanationLevel:"Niveau d’explication",simple:"Simple",standard:"Standard",detailed:"Détaillé",readyWhen:"Quand vous voulez.",disclosure:"Le texte extrait—pas le fichier original—sera envoyé à OpenAI.",explain:"Expliquer ce document",newDocument:"Nouveau document",linked:"Les détails clés sont reliés au texte original",extraLook:"Vérifiez attentivement",whatIs:"QU’EST-CE QUE C’EST ?",plain:"En langage clair",needKnow:"À RETENIR",important:"Les points importants",deadlines:"ÉCHÉANCES",needDo:"CE QUE VOUS DEVEZ FAIRE",nextSteps:"Vos prochaines étapes",checkOriginal:"Vérifiez l’original",privateDesign:"Confidentiel par conception",settingsTitle:"Réglages auto-hébergés",settingsCopy:"Utilisez la clé serveur OPENAI_API_KEY ou saisissez une clé pour cette session uniquement. Elle n’est jamais enregistrée sur disque.",apiKey:"Clé API OpenAI",saveSession:"Utiliser pour cette session",clearKey:"Effacer la clé",keyReady:"Une clé API serveur est configurée.",keySessionReady:"La clé de session est prête.",keyMissing:"Ajoutez une clé API avant l’analyse.",close:"Fermer",footer:"Comprendoc aide à comprendre les documents, mais l’IA peut se tromper. Vérifiez les dates, délais et exigences dans l’original.",footerMeta:"Conçu pour le bien · Sans compte · Aucun document stocké" },
  ar: { privacy:"الخصوصية",how:"كيف يعمل",demo:"عرض تجريبي",settings:"الإعدادات",tagline:"افهم المستندات. وتصرف فيما يهم.",hero1:"افهم الأوراق المعقدة.",hero2:"واعرف خطوتك التالية.",heroCopy:"يحوّل Comprendoc المستندات المعقدة إلى شرح واضح بلغتك ويساعدك على متابعة ما يهم.",demoTitle:"استكشف عرض Comprendoc",demoCopy:"يستخدم هذا الموقع العام أمثلة اصطناعية فقط ولا يقبل مستندات أو يجري طلبات ذكاء اصطناعي مدفوعة.",demoButton:"عرض مستند تجريبي",drop:"أفلت مستندًا هنا",choose:"اختر ملفًا",or:"أو",paste:"الصق نصًا",filePrivate:"يبقى ملفك في متصفحك.",filePrivate2:"يُرسل النص المستخرج فقط للتحليل.",tryExample:"جرّب مثالًا",seeAction:"شاهد Comprendoc أثناء العمل",synthetic:"مستندات اصطناعية بلا معلومات شخصية.",howLabel:"كيف يعمل",howTitle:"من التعقيد إلى خطوة تالية واضحة",step1:"أضف مستندك",step1Copy:"ارفع أو الصق. الملف الأصلي لا يغادر المتصفح.",step2:"اختر لغتك",step2Copy:"احصل على شرح طبيعي بالمستوى المناسب لك.",step3:"تصرّف بثقة",step3Copy:"شاهد المواعيد وتحقق من المصادر وأضف التواريخ إلى التقويم.",startOver:"ابدأ من جديد",ready:"المستند جاهز",explainHow:"كيف نشرحه؟",extracted:"استُخرج النص محليًا. اختر ما يناسبك.",explanationLanguage:"لغة الشرح",explanationLevel:"مستوى الشرح",simple:"بسيط",standard:"متوسط",detailed:"مفصل",readyWhen:"جاهز عندما تكون جاهزًا.",disclosure:"سيُرسل النص المستخرج—وليس الملف الأصلي—إلى OpenAI للتحليل.",explain:"اشرح هذا المستند",newDocument:"مستند جديد",linked:"التفاصيل المهمة مرتبطة بالنص الأصلي",extraLook:"ألقِ نظرة إضافية",whatIs:"ما هذا؟",plain:"بلغة بسيطة",needKnow:"ما تحتاج إلى معرفته",important:"النقاط المهمة",deadlines:"المواعيد النهائية",needDo:"ما عليك فعله",nextSteps:"خطواتك التالية",checkOriginal:"راجع الأصل",privateDesign:"خصوصية مدمجة",settingsTitle:"إعدادات الاستضافة الذاتية",settingsCopy:"استخدم مفتاح الخادم OPENAI_API_KEY أو أدخل مفتاحًا لهذه الجلسة فقط. لا يُحفظ على القرص.",apiKey:"مفتاح OpenAI API",saveSession:"استخدم لهذه الجلسة",clearKey:"امسح مفتاح الجلسة",keyReady:"تم إعداد مفتاح API على الخادم.",keySessionReady:"مفتاح الجلسة جاهز.",keyMissing:"أضف مفتاح API قبل التحليل.",close:"إغلاق",footer:"يساعدك Comprendoc على فهم المستندات، لكن الذكاء الاصطناعي قد يخطئ. تحقق من التواريخ والمتطلبات في الأصل.",footerMeta:"صُمم للخير · بلا حسابات · بلا تخزين للمستندات" },
  pt: { privacy:"Privacidade",how:"Como funciona",demo:"Demo",settings:"Configurações",tagline:"Compreenda os documentos. Aja no que importa.",hero1:"Entenda a papelada.",hero2:"Saiba o que fazer a seguir.",heroCopy:"O Comprendoc transforma documentos complicados em explicações claras no seu idioma e acompanha o que importa.",demoTitle:"Explore a demonstração",demoCopy:"Este site público usa apenas exemplos sintéticos. Não aceita documentos nem faz solicitações pagas de IA.",demoButton:"Ver documento de demonstração",drop:"Solte um documento aqui",choose:"Escolher arquivo",or:"ou",paste:"Colar texto",filePrivate:"Seu arquivo fica no navegador.",filePrivate2:"Só o texto extraído é enviado para análise.",tryExample:"EXPERIMENTE UM EXEMPLO",seeAction:"Veja o Comprendoc em ação",synthetic:"Documentos sintéticos. Sem dados pessoais.",howLabel:"COMO FUNCIONA",howTitle:"Da burocracia ao próximo passo",step1:"Adicione seu documento",step1Copy:"Envie ou cole. O arquivo original não sai do navegador.",step2:"Escolha seu idioma",step2Copy:"Receba uma explicação natural no nível ideal.",step3:"Aja com confiança",step3Copy:"Veja prazos, confira fontes e adicione datas ao calendário.",startOver:"Recomeçar",ready:"DOCUMENTO PRONTO",explainHow:"Como devemos explicar?",extracted:"O texto foi extraído localmente. Escolha o que for melhor.",explanationLanguage:"Idioma da explicação",explanationLevel:"Nível da explicação",simple:"Simples",standard:"Padrão",detailed:"Detalhado",readyWhen:"Quando você estiver pronto.",disclosure:"O texto extraído—não o arquivo original—será enviado à OpenAI.",explain:"Explicar este documento",newDocument:"Novo documento",linked:"Detalhes importantes estão ligados ao texto original",extraLook:"Confira com atenção",whatIs:"O QUE É ISTO?",plain:"Em linguagem simples",needKnow:"O QUE VOCÊ PRECISA SABER",important:"Pontos importantes",deadlines:"PRAZOS",needDo:"O QUE VOCÊ PRECISA FAZER",nextSteps:"Próximos passos",checkOriginal:"Confira o original",privateDesign:"Privacidade por design",settingsTitle:"Configurações auto-hospedadas",settingsCopy:"Use a chave do servidor OPENAI_API_KEY ou informe uma chave só para esta sessão. Ela nunca é salva em disco.",apiKey:"Chave da API OpenAI",saveSession:"Usar nesta sessão",clearKey:"Limpar chave",keyReady:"Uma chave de API está configurada no servidor.",keySessionReady:"A chave da sessão está pronta.",keyMissing:"Adicione uma chave antes de analisar.",close:"Fechar",footer:"O Comprendoc ajuda a entender documentos, mas a IA pode errar. Confira datas, prazos e exigências no original.",footerMeta:"Feito para o bem · Sem contas · Sem armazenar documentos" },
};

// Closely related locales intentionally fall back to English for any untranslated
// secondary label while retaining fully localized navigation and primary flows.
translations.de = { privacy:"Datenschutz",how:"So funktioniert es",demo:"Demo",settings:"Einstellungen",tagline:"Dokumente verstehen. Das Wichtige erledigen.",hero1:"Den Papierkram verstehen.",hero2:"Wissen, was als Nächstes zu tun ist.",heroCopy:"Comprendoc verwandelt komplizierte Dokumente in klare Erklärungen in deiner Sprache und hilft dir, das Wichtige im Blick zu behalten.",demoTitle:"Comprendoc-Demo entdecken",demoCopy:"Diese öffentliche Website verwendet nur synthetische Beispiele. Sie nimmt keine Dokumente an und sendet keine kostenpflichtigen KI-Anfragen.",demoButton:"Demodokument ansehen",drop:"Dokument hier ablegen",formats:"PDF, DOCX oder TXT · bis zu 25 MB",choose:"Datei auswählen",or:"oder",paste:"Text einfügen",closePaste:"Textfeld schließen",pasteLabel:"Dokumenttext einfügen",pastePlaceholder:"Brief, Bescheid oder Formulartext hier einfügen…",useText:"Diesen Text verwenden",filePrivate:"Deine Datei bleibt im Browser.",filePrivate2:"Nur der extrahierte Text wird zur KI-Analyse gesendet.",tryExample:"BEISPIEL AUSPROBIEREN",seeAction:"Comprendoc in Aktion",synthetic:"Synthetische Dokumente. Keine personenbezogenen Daten.",howLabel:"SO FUNKTIONIERT ES",howTitle:"Vom Papierkram zum klaren nächsten Schritt",step1:"Dokument hinzufügen",step1Copy:"Hochladen oder einfügen. Die Originaldatei verlässt den Browser nicht.",step2:"Sprache auswählen",step2Copy:"Eine natürliche Erklärung im passenden Detailgrad erhalten.",step3:"Sicher handeln",step3Copy:"Fristen erkennen, Quellen prüfen und Termine zum Kalender hinzufügen.",startOver:"Neu beginnen",ready:"DOKUMENT BEREIT",explainHow:"Wie sollen wir es erklären?",extracted:"Der Dokumenttext wurde lokal extrahiert. Wähle die passende Darstellung.",explanationLanguage:"Sprache der Erklärung",explanationLevel:"Detailgrad",simple:"Einfach",standard:"Standard",detailed:"Ausführlich",simpleHint:"Kurz und klar",standardHint:"Ausgewogen",detailedHint:"Mehr Kontext",readyWhen:"Bereit, wenn du es bist.",disclosure:"Der extrahierte Text – nicht die Originaldatei – wird zur Analyse an {provider} gesendet.",explain:"Dokument erklären",newDocument:"Neues Dokument",linked:"Wichtige Details sind mit dem Originaltext verknüpft",extraLook:"Bitte besonders prüfen",whatIs:"WAS IST DAS?",plain:"Einfach erklärt",needKnow:"WAS DU WISSEN MUSST",important:"Die wichtigsten Punkte",deadlines:"FRISTEN",needDo:"WAS DU TUN MUSST",nextSteps:"Deine nächsten Schritte",checkOriginal:"Original prüfen",checkCopy:"KI kann Fehler machen. Prüfe wichtige Daten und Anforderungen im Originaldokument.",privateDesign:"Datenschutz von Grund auf",footer:"Comprendoc hilft beim Verstehen von Dokumenten, aber KI kann Fehler machen. Prüfe wichtige Daten, Fristen und Anforderungen im Original.",footerMeta:"Für das Gute entwickelt · Keine Konten · Keine Dokumentenspeicherung" };
translations.hi = { privacy:"गोपनीयता",how:"यह कैसे काम करता है",demo:"डेमो",settings:"सेटिंग्स",tagline:"दस्तावेज़ समझें। ज़रूरी काम करें।",hero1:"कागज़ात को समझें।",hero2:"अगला कदम जानें।",heroCopy:"Comprendoc कठिन दस्तावेज़ों को आपकी भाषा में साफ़ समझाता है।",demoTitle:"Comprendoc डेमो देखें",demoCopy:"यह सार्वजनिक साइट केवल नकली उदाहरण दिखाती है। कोई दस्तावेज़ या सशुल्क AI अनुरोध नहीं।",demoButton:"डेमो दस्तावेज़ देखें",choose:"फ़ाइल चुनें",tryExample:"उदाहरण आज़माएँ",seeAction:"Comprendoc को काम करते देखें",startOver:"फिर से शुरू करें",explanationLanguage:"समझाने की भाषा",explanationLevel:"विवरण स्तर",explain:"दस्तावेज़ समझाएँ",settingsTitle:"सेल्फ-होस्टेड सेटिंग्स",apiKey:"OpenAI API कुंजी",saveSession:"इस सत्र में उपयोग करें",clearKey:"सत्र कुंजी हटाएँ",keyMissing:"विश्लेषण से पहले API कुंजी जोड़ें।",close:"बंद करें" };
translations.ru = { privacy:"Конфиденциальность",how:"Как это работает",demo:"Демо",settings:"Настройки",tagline:"Поймите документы. Сделайте главное.",hero1:"Разберитесь в документах.",hero2:"Узнайте, что делать дальше.",heroCopy:"Comprendoc превращает сложные документы в понятные объяснения на вашем языке.",demoTitle:"Демо Comprendoc",demoCopy:"Публичный сайт показывает только искусственные примеры. Загрузка документов и платные запросы ИИ отключены.",demoButton:"Открыть демо-документ",choose:"Выбрать файл",tryExample:"ПОПРОБОВАТЬ ПРИМЕР",seeAction:"Comprendoc в действии",startOver:"Начать сначала",explanationLanguage:"Язык объяснения",explanationLevel:"Уровень объяснения",explain:"Объяснить документ",newDocument:"Новый документ",settingsTitle:"Настройки самостоятельного хостинга",apiKey:"Ключ OpenAI API",saveSession:"Использовать в этой сессии",clearKey:"Удалить ключ",keyMissing:"Добавьте ключ API перед анализом.",close:"Закрыть" };
translations.vi = { privacy:"Quyền riêng tư",how:"Cách hoạt động",demo:"Bản thử",settings:"Cài đặt",tagline:"Hiểu tài liệu. Hành động đúng việc.",hero1:"Hiểu giấy tờ.",hero2:"Biết bước tiếp theo.",heroCopy:"Comprendoc biến tài liệu phức tạp thành lời giải thích rõ ràng bằng ngôn ngữ của bạn.",demoTitle:"Khám phá bản thử Comprendoc",demoCopy:"Trang công khai này chỉ dùng ví dụ tổng hợp, không nhận tài liệu hay gọi AI trả phí.",demoButton:"Xem tài liệu mẫu",choose:"Chọn tệp",tryExample:"THỬ MỘT VÍ DỤ",seeAction:"Xem Comprendoc hoạt động",startOver:"Bắt đầu lại",explanationLanguage:"Ngôn ngữ giải thích",explanationLevel:"Mức giải thích",explain:"Giải thích tài liệu",settingsTitle:"Cài đặt tự lưu trữ",apiKey:"Khóa OpenAI API",saveSession:"Dùng trong phiên này",clearKey:"Xóa khóa phiên",keyMissing:"Hãy thêm khóa API trước khi phân tích.",close:"Đóng" };
translations.ja = { privacy:"プライバシー",how:"使い方",demo:"デモ",settings:"設定",tagline:"書類を理解し、大切なことに行動を。",hero1:"複雑な書類を理解。",hero2:"次にすることが分かる。",heroCopy:"Comprendoc は複雑な書類をあなたの言語で分かりやすく説明します。",demoTitle:"Comprendoc デモを体験",demoCopy:"公開サイトでは合成サンプルのみを使用し、書類の受付や有料 AI リクエストは行いません。",demoButton:"デモ書類を見る",choose:"ファイルを選ぶ",tryExample:"サンプルを試す",seeAction:"Comprendoc の動作を見る",startOver:"最初から",explanationLanguage:"説明の言語",explanationLevel:"説明レベル",simple:"簡潔",standard:"標準",detailed:"詳細",explain:"この書類を説明",newDocument:"新しい書類",settingsTitle:"セルフホスト設定",apiKey:"OpenAI API キー",saveSession:"このセッションで使用",clearKey:"セッションキーを削除",keyMissing:"分析前に API キーを追加してください。",close:"閉じる" };
translations.ko = { privacy:"개인정보",how:"사용 방법",demo:"데모",settings:"설정",tagline:"문서를 이해하고 중요한 일에 집중하세요.",hero1:"복잡한 서류를 이해하세요.",hero2:"다음 할 일을 확인하세요.",heroCopy:"Comprendoc은 복잡한 문서를 사용자의 언어로 명확하게 설명합니다.",demoTitle:"Comprendoc 데모 체험",demoCopy:"공개 사이트는 합성 예시만 사용하며 문서를 받거나 유료 AI 요청을 하지 않습니다.",demoButton:"데모 문서 보기",choose:"파일 선택",tryExample:"예시 사용해 보기",seeAction:"Comprendoc 작동 방식 보기",startOver:"다시 시작",explanationLanguage:"설명 언어",explanationLevel:"설명 수준",simple:"간단히",standard:"표준",detailed:"자세히",explain:"문서 설명하기",newDocument:"새 문서",settingsTitle:"셀프 호스팅 설정",apiKey:"OpenAI API 키",saveSession:"이 세션에서 사용",clearKey:"세션 키 삭제",keyMissing:"분석 전에 API 키를 추가하세요.",close:"닫기" };
translations.ko = { ...translations.ko, readyWhen:"준비되었습니다.",disclosure:"추출된 문서 텍스트(원본 파일이 아님)는 분석을 위해 {provider}에 전송됩니다." };

export function messages(locale: Locale): Messages {
  return { ...en, ...(translations[locale] || {}) };
}

export function providerDisclosure(message: string, providerName: string): string {
  return message.replace("{provider}", providerName).replace("OpenAI", providerName);
}

export function detectLocale(languageTags: readonly string[]): Locale {
  for (const tag of languageTags) {
    const normalized = tag.toLowerCase().replaceAll("_", "-");
    const exact = uiLanguages.find((item) => item.code.toLowerCase() === normalized);
    if (exact) return exact.code;
    if (normalized.startsWith("zh-") && /-(tw|hk|mo|hant)(-|$)/.test(normalized)) return "zh-TW";
    if (normalized.startsWith("zh-") && /-(cn|sg|hans)(-|$)/.test(normalized)) return "zh-CN";
    const base = normalized.split("-")[0];
    const match = uiLanguages.find((item) => item.code.toLowerCase().split("-")[0] === base);
    if (match) return match.code;
  }
  return "en";
}
