const locales = ["en", "zh-CN", "zh-TW", "fr", "de", "ko"];

const copy = {
  en: { navLabel:"Main navigation",how:"How it works",language:"Language",demo:"Demo",tagline:"Comprehend the docs. Act on what matters.",hero1:"Understand the paperwork.",hero2:"Know what to do next.",heroCopy:"Explore how Comprendoc turns a complicated document into a clear explanation, deadlines, and next steps.",safeDemo:"Safe interactive demo",safeCopy:"Synthetic documents only. No uploads, API calls, accounts, or saved data.",tryExample:"TRY AN EXAMPLE",chooseExample:"Choose a sample document",chooseCopy:"See a complete processed result without sending anything anywhere.",howLabel:"HOW IT WORKS",howTitle:"From red tape to a clear next step",step1:"Add your document",step1Copy:"The self-hosted app reads PDF, DOCX, TXT, or pasted text locally.",step2:"Choose your language",step2Copy:"Select an explanation language and the level of detail you prefer.",step3:"Act with confidence",step3Copy:"Review deadlines, actions, source wording, and calendar-ready dates.",footer:"AI can make mistakes. Verify important details against the original document.",footerMeta:"Static demo · No data leaves your browser",open:"View processed result",back:"Back to examples",processed:"Processed example",what:"WHAT IS THIS?",plain:"In plain language",know:"WHAT YOU NEED TO KNOW",important:"Important points",deadlines:"DEADLINES",next:"WHAT TO DO NEXT",actions:"Your next steps",source:"ORIGINAL SAMPLE TEXT",showSource:"Show exact wording",hideSource:"Hide exact wording",check:"Check the original",checkCopy:"AI can make mistakes. Always verify dates and requirements against the source document.",private:"Demo privacy",privateCopy:"This static demo makes no network requests and stores no data." },
  "zh-CN": { navLabel:"主导航",how:"使用方法",language:"语言",demo:"演示",tagline:"读懂文件，把握要事。",hero1:"看懂复杂文件。",hero2:"清楚下一步该做什么。",heroCopy:"体验 Comprendoc 如何把复杂文件变成清晰说明、截止日期和下一步行动。",safeDemo:"安全互动演示",safeCopy:"仅使用合成文件，不上传、不调用接口、无需账户，也不保存数据。",tryExample:"试用示例",chooseExample:"选择一份示例文件",chooseCopy:"无需发送任何内容，即可查看完整处理结果。",howLabel:"使用方法",howTitle:"从繁文缛节到清晰行动",step1:"添加文件",step1Copy:"自托管应用会在本地读取 PDF、DOCX、TXT 或粘贴文本。",step2:"选择语言",step2Copy:"选择说明语言和适合你的详细程度。",step3:"安心行动",step3Copy:"查看截止日期、行动、原文措辞和可添加到日历的日期。",footer:"AI 可能出错，请对照原文件核实重要细节。",footerMeta:"静态演示 · 数据不会离开浏览器",open:"查看处理结果",back:"返回示例",processed:"已处理示例",what:"这是什么？",plain:"简单说明",know:"你需要知道",important:"重点",deadlines:"截止日期",next:"下一步该做什么",actions:"你的下一步",source:"示例原文",showSource:"查看准确措辞",hideSource:"隐藏准确措辞",check:"核对原文",checkCopy:"AI 可能出错，请务必对照原文件核实日期和要求。",private:"演示隐私",privateCopy:"此静态演示不会发起网络请求，也不会保存数据。" },
  "zh-TW": { navLabel:"主導覽",how:"運作方式",language:"語言",demo:"示範",tagline:"讀懂文件，掌握重點。",hero1:"看懂複雜文件。",hero2:"清楚下一步該做什麼。",heroCopy:"體驗 Comprendoc 如何將複雜文件轉化為清楚說明、期限與下一步行動。",safeDemo:"安全互動示範",safeCopy:"僅使用合成文件，不上傳、不呼叫介面、無需帳號，也不儲存資料。",tryExample:"試用範例",chooseExample:"選擇一份範例文件",chooseCopy:"無需傳送任何內容，即可查看完整處理結果。",howLabel:"運作方式",howTitle:"從繁瑣文件到清楚行動",step1:"加入文件",step1Copy:"自架應用程式會在本機讀取 PDF、DOCX、TXT 或貼上的文字。",step2:"選擇語言",step2Copy:"選擇說明語言和適合你的詳細程度。",step3:"安心採取行動",step3Copy:"查看期限、行動、原文措辭和可加入行事曆的日期。",footer:"AI 可能出錯，請對照原始文件核實重要細節。",footerMeta:"靜態示範 · 資料不會離開瀏覽器",open:"查看處理結果",back:"返回範例",processed:"已處理範例",what:"這是什麼？",plain:"白話說明",know:"你需要知道",important:"重要重點",deadlines:"截止期限",next:"下一步該做什麼",actions:"你的下一步",source:"範例原文",showSource:"查看準確措辭",hideSource:"隱藏準確措辭",check:"核對原文",checkCopy:"AI 可能出錯，請務必對照原始文件核實日期與要求。",private:"示範隱私",privateCopy:"此靜態示範不會發出網路請求，也不會儲存資料。" },
  fr: { navLabel:"Navigation principale",how:"Fonctionnement",language:"Langue",demo:"Démo",tagline:"Comprenez les documents. Agissez sur l’essentiel.",hero1:"Comprenez les démarches.",hero2:"Sachez quoi faire ensuite.",heroCopy:"Découvrez comment Comprendoc transforme un document complexe en explication claire, échéances et prochaines étapes.",safeDemo:"Démo interactive sûre",safeCopy:"Documents fictifs uniquement. Aucun import, appel API, compte ou stockage.",tryExample:"ESSAYER UN EXEMPLE",chooseExample:"Choisissez un document exemple",chooseCopy:"Consultez un résultat complet sans rien envoyer.",howLabel:"FONCTIONNEMENT",howTitle:"Des formalités à une prochaine étape claire",step1:"Ajoutez votre document",step1Copy:"L’application auto-hébergée lit localement les PDF, DOCX, TXT ou textes collés.",step2:"Choisissez votre langue",step2Copy:"Choisissez la langue et le niveau de détail de l’explication.",step3:"Agissez en confiance",step3Copy:"Consultez les échéances, actions, sources et dates prêtes pour le calendrier.",footer:"L’IA peut se tromper. Vérifiez les détails importants dans le document original.",footerMeta:"Démo statique · Aucune donnée ne quitte le navigateur",open:"Voir le résultat",back:"Retour aux exemples",processed:"Exemple traité",what:"QU’EST-CE QUE C’EST ?",plain:"En langage simple",know:"CE QU’IL FAUT SAVOIR",important:"Points importants",deadlines:"ÉCHÉANCES",next:"PROCHAINES ACTIONS",actions:"Vos prochaines étapes",source:"TEXTE ORIGINAL DE L’EXEMPLE",showSource:"Afficher les termes exacts",hideSource:"Masquer les termes exacts",check:"Vérifiez l’original",checkCopy:"L’IA peut se tromper. Vérifiez toujours les dates et exigences dans le document source.",private:"Confidentialité de la démo",privateCopy:"Cette démo statique n’effectue aucune requête réseau et ne stocke rien." },
  de: { navLabel:"Hauptnavigation",how:"So funktioniert es",language:"Sprache",demo:"Demo",tagline:"Dokumente verstehen. Das Wichtige erledigen.",hero1:"Papierkram verstehen.",hero2:"Den nächsten Schritt kennen.",heroCopy:"Erlebe, wie Comprendoc ein kompliziertes Dokument in eine klare Erklärung, Fristen und nächste Schritte verwandelt.",safeDemo:"Sichere interaktive Demo",safeCopy:"Nur synthetische Dokumente. Keine Uploads, API-Aufrufe, Konten oder Speicherung.",tryExample:"BEISPIEL TESTEN",chooseExample:"Beispieldokument auswählen",chooseCopy:"Sieh ein vollständiges Ergebnis, ohne etwas zu versenden.",howLabel:"SO FUNKTIONIERT ES",howTitle:"Vom Papierkram zum klaren nächsten Schritt",step1:"Dokument hinzufügen",step1Copy:"Die selbst gehostete App liest PDF, DOCX, TXT oder eingefügten Text lokal.",step2:"Sprache wählen",step2Copy:"Wähle Sprache und Detailgrad der Erklärung.",step3:"Sicher handeln",step3Copy:"Prüfe Fristen, Aufgaben, Quelltext und kalenderfertige Termine.",footer:"KI kann Fehler machen. Prüfe wichtige Angaben im Originaldokument.",footerMeta:"Statische Demo · Keine Daten verlassen den Browser",open:"Ergebnis ansehen",back:"Zurück zu den Beispielen",processed:"Verarbeitetes Beispiel",what:"WAS IST DAS?",plain:"Einfach erklärt",know:"WAS DU WISSEN MUSST",important:"Wichtige Punkte",deadlines:"FRISTEN",next:"NÄCHSTE SCHRITTE",actions:"Deine nächsten Schritte",source:"ORIGINALTEXT DES BEISPIELS",showSource:"Genauen Wortlaut anzeigen",hideSource:"Genauen Wortlaut ausblenden",check:"Original prüfen",checkCopy:"KI kann Fehler machen. Prüfe Termine und Anforderungen immer im Quelldokument.",private:"Datenschutz der Demo",privateCopy:"Diese statische Demo sendet keine Netzwerkanfragen und speichert keine Daten." },
  ko: { navLabel:"주요 탐색",how:"이용 방법",language:"언어",demo:"데모",tagline:"문서를 이해하고 중요한 일에 집중하세요.",hero1:"복잡한 서류를 이해하세요.",hero2:"다음 할 일을 확인하세요.",heroCopy:"Comprendoc이 복잡한 문서를 명확한 설명, 마감일, 다음 단계로 바꾸는 모습을 체험하세요.",safeDemo:"안전한 대화형 데모",safeCopy:"합성 문서만 사용합니다. 업로드, API 호출, 계정, 데이터 저장이 없습니다.",tryExample:"예시 사용",chooseExample:"예시 문서를 선택하세요",chooseCopy:"아무것도 전송하지 않고 전체 처리 결과를 확인하세요.",howLabel:"이용 방법",howTitle:"복잡한 서류에서 명확한 다음 단계로",step1:"문서 추가",step1Copy:"셀프 호스팅 앱은 PDF, DOCX, TXT 또는 붙여 넣은 텍스트를 로컬에서 읽습니다.",step2:"언어 선택",step2Copy:"설명 언어와 원하는 상세 수준을 선택하세요.",step3:"안심하고 행동",step3Copy:"마감일, 할 일, 원문 표현, 캘린더용 날짜를 확인하세요.",footer:"AI는 실수할 수 있습니다. 중요한 내용은 원본 문서와 대조하세요.",footerMeta:"정적 데모 · 데이터가 브라우저를 벗어나지 않음",open:"처리 결과 보기",back:"예시로 돌아가기",processed:"처리된 예시",what:"이 문서는 무엇인가요?",plain:"쉽게 설명",know:"알아야 할 내용",important:"중요 사항",deadlines:"마감일",next:"다음에 할 일",actions:"다음 단계",source:"예시 원문",showSource:"정확한 문구 보기",hideSource:"정확한 문구 숨기기",check:"원본 확인",checkCopy:"AI는 실수할 수 있습니다. 날짜와 요구 사항을 원본 문서와 대조하세요.",private:"데모 개인정보 보호",privateCopy:"이 정적 데모는 네트워크 요청을 보내거나 데이터를 저장하지 않습니다." }
};

const documents = {
  en: [
    {icon:"▤",type:"University enrollment notice",title:"International student enrollment steps",card:"Three dates and four required steps",summary:"Submit the enrollment form, pay the deposit, provide the requested documents, and attend orientation.",plain:"This notice explains what an international student must complete before enrollment is finalized.",points:["The enrollment form must be submitted first.","A deposit and identity documents are required.","Orientation attendance is mandatory."],deadline:{date:"August 28, 2026",action:"Submit the enrollment form and supporting documents."},actions:["Complete and review the enrollment form.","Upload the requested identity and visa documents.","Pay the enrollment deposit before the deadline."],source:"International Student Office\n\nPlease return the completed enrollment form and all supporting documents by August 28, 2026. Your enrollment deposit must be received by the same date. Attendance at orientation on September 3, 2026 is required."},
    {icon:"⌂",type:"Housing notice",title:"Income verification request",card:"A deadline based on when the notice arrives",summary:"Return the income verification form within 10 business days after receiving the notice.",plain:"Your housing office needs updated proof of income. The exact deadline depends on the date you received this notice.",points:["The response period is 10 business days.","Recent pay slips or benefit statements are accepted.","Missing the deadline may delay the application."],deadline:{date:"10 business days after receipt",action:"Return the form with current proof of income."},actions:["Write down the date you received the notice.","Collect current income documents.","Submit the completed form within 10 business days."],source:"Income Verification Request\n\nWithin 10 business days of receiving this notice, return the enclosed form with your two most recent pay statements or current benefit letter. Failure to respond may delay processing of your housing application."}
  ],
  "zh-CN": [
    {icon:"▤",type:"大学入学通知",title:"国际学生入学步骤",card:"三个日期和四项必要步骤",summary:"提交入学表格、支付押金、提供所需文件并参加说明会。",plain:"这份通知说明国际学生在完成入学前必须办理的事项。",points:["必须先提交入学表格。","需要支付押金并提供身份证明文件。","必须参加入学说明会。"],deadline:{date:"2026年8月28日",action:"提交入学表格和证明文件。"},actions:["填写并核对入学表格。","上传所需的身份和签证文件。","在截止日期前支付入学押金。"],source:"国际学生办公室\n\n请在2026年8月28日前交回完整的入学表格和所有证明文件。入学押金也必须在当天前到账。必须参加2026年9月3日的入学说明会。"},
    {icon:"⌂",type:"住房通知",title:"收入证明请求",card:"截止日期取决于收到通知的时间",summary:"请在收到通知后的10个工作日内交回收入证明表格。",plain:"住房办公室需要最新收入证明。确切截止日期取决于你收到通知的日期。",points:["回复期限为10个工作日。","可提交近期工资单或福利证明。","错过期限可能延误申请。"],deadline:{date:"收到通知后10个工作日",action:"交回表格和最新收入证明。"},actions:["记录收到通知的日期。","准备最新收入文件。","在10个工作日内提交完整表格。"],source:"收入证明请求\n\n请在收到本通知后的10个工作日内，交回随附表格以及最近两份工资单或最新福利证明。未按时回复可能延误住房申请的处理。"}
  ],
  "zh-TW": [
    {icon:"▤",type:"大學入學通知",title:"國際學生入學步驟",card:"三個日期和四項必要步驟",summary:"提交入學表格、支付訂金、提供所需文件並參加入學說明會。",plain:"這份通知說明國際學生在完成入學前必須辦理的事項。",points:["必須先提交入學表格。","需要支付訂金並提供身分證明文件。","必須參加入學說明會。"],deadline:{date:"2026年8月28日",action:"提交入學表格和證明文件。"},actions:["填寫並核對入學表格。","上傳所需的身分和簽證文件。","在期限前支付入學訂金。"],source:"國際學生辦公室\n\n請在2026年8月28日前交回完整的入學表格和所有證明文件。入學訂金也必須在當天前入帳。必須參加2026年9月3日的入學說明會。"},
    {icon:"⌂",type:"住房通知",title:"收入證明要求",card:"期限取決於收到通知的時間",summary:"請在收到通知後的10個工作天內交回收入證明表格。",plain:"住房辦公室需要最新收入證明。確切期限取決於你收到通知的日期。",points:["回覆期限為10個工作天。","可提交近期薪資單或福利證明。","錯過期限可能延誤申請。"],deadline:{date:"收到通知後10個工作天",action:"交回表格和最新收入證明。"},actions:["記錄收到通知的日期。","準備最新收入文件。","在10個工作天內提交完整表格。"],source:"收入證明要求\n\n請在收到本通知後的10個工作天內，交回隨附表格以及最近兩份薪資單或最新福利證明。未按時回覆可能延誤住房申請的處理。"}
  ],
  fr: [
    {icon:"▤",type:"Avis d’inscription universitaire",title:"Étapes d’inscription des étudiants internationaux",card:"Trois dates et quatre étapes obligatoires",summary:"Envoyez le formulaire, payez l’acompte, fournissez les documents demandés et assistez à l’orientation.",plain:"Cet avis explique ce qu’un étudiant international doit accomplir avant la validation de son inscription.",points:["Le formulaire d’inscription doit être envoyé en premier.","Un acompte et des justificatifs d’identité sont requis.","La présence à l’orientation est obligatoire."],deadline:{date:"28 août 2026",action:"Envoyer le formulaire d’inscription et les justificatifs."},actions:["Remplir et vérifier le formulaire.","Téléverser les pièces d’identité et de visa demandées.","Payer l’acompte avant l’échéance."],source:"Bureau des étudiants internationaux\n\nVeuillez renvoyer le formulaire d’inscription complet et tous les justificatifs avant le 28 août 2026. L’acompte doit être reçu à la même date. La présence à l’orientation du 3 septembre 2026 est obligatoire."},
    {icon:"⌂",type:"Avis de logement",title:"Demande de justificatif de revenus",card:"Une échéance liée à la date de réception",summary:"Renvoyez le formulaire dans les 10 jours ouvrables suivant la réception de l’avis.",plain:"Le service du logement demande un justificatif de revenus à jour. La date exacte dépend de la réception de l’avis.",points:["Le délai de réponse est de 10 jours ouvrables.","Les fiches de paie ou attestations de prestations récentes sont acceptées.","Un retard peut retarder la demande."],deadline:{date:"10 jours ouvrables après réception",action:"Renvoyer le formulaire avec un justificatif de revenus actuel."},actions:["Noter la date de réception.","Rassembler les justificatifs actuels.","Envoyer le formulaire complet sous 10 jours ouvrables."],source:"Demande de justificatif de revenus\n\nDans les 10 jours ouvrables suivant la réception de cet avis, renvoyez le formulaire joint avec vos deux dernières fiches de paie ou votre attestation de prestations actuelle. Une absence de réponse peut retarder votre demande de logement."}
  ],
  de: [
    {icon:"▤",type:"Mitteilung zur Einschreibung",title:"Schritte zur Einschreibung internationaler Studierender",card:"Drei Termine und vier erforderliche Schritte",summary:"Reiche das Formular ein, zahle die Kaution, sende die Unterlagen und nimm an der Orientierung teil.",plain:"Diese Mitteilung erklärt, was internationale Studierende vor Abschluss der Einschreibung erledigen müssen.",points:["Das Einschreibeformular muss zuerst eingereicht werden.","Kaution und Identitätsnachweise sind erforderlich.","Die Teilnahme an der Orientierung ist verpflichtend."],deadline:{date:"28. August 2026",action:"Einschreibeformular und Nachweise einreichen."},actions:["Formular ausfüllen und prüfen.","Geforderte Identitäts- und Visadokumente hochladen.","Kaution vor Ablauf der Frist zahlen."],source:"Büro für internationale Studierende\n\nBitte reiche das vollständige Einschreibeformular und alle Nachweise bis zum 28. August 2026 ein. Die Kaution muss bis zum selben Datum eingegangen sein. Die Teilnahme an der Orientierung am 3. September 2026 ist verpflichtend."},
    {icon:"⌂",type:"Wohnungsmitteilung",title:"Anforderung eines Einkommensnachweises",card:"Eine Frist ab Erhalt der Mitteilung",summary:"Sende das Formular innerhalb von 10 Werktagen nach Erhalt zurück.",plain:"Die Wohnungsstelle benötigt einen aktuellen Einkommensnachweis. Die genaue Frist hängt vom Empfangsdatum ab.",points:["Die Antwortfrist beträgt 10 Werktage.","Aktuelle Lohnabrechnungen oder Leistungsbescheide werden akzeptiert.","Eine verspätete Antwort kann den Antrag verzögern."],deadline:{date:"10 Werktage nach Erhalt",action:"Formular mit aktuellem Einkommensnachweis zurücksenden."},actions:["Empfangsdatum notieren.","Aktuelle Einkommensunterlagen sammeln.","Vollständiges Formular innerhalb von 10 Werktagen einreichen."],source:"Anforderung eines Einkommensnachweises\n\nSende innerhalb von 10 Werktagen nach Erhalt dieser Mitteilung das beigefügte Formular mit deinen zwei neuesten Lohnabrechnungen oder dem aktuellen Leistungsbescheid zurück. Eine fehlende Antwort kann die Bearbeitung des Wohnungsantrags verzögern."}
  ],
  ko: [
    {icon:"▤",type:"대학 등록 안내",title:"유학생 등록 단계",card:"중요한 날짜 세 개와 필수 단계 네 개",summary:"등록 양식을 제출하고 예치금을 납부한 뒤 요청 문서를 제공하고 오리엔테이션에 참석하세요.",plain:"이 안내문은 유학생 등록 완료 전에 해야 할 일을 설명합니다.",points:["등록 양식을 먼저 제출해야 합니다.","예치금과 신분 증명 문서가 필요합니다.","오리엔테이션 참석은 필수입니다."],deadline:{date:"2026년 8월 28일",action:"등록 양식과 증빙 문서를 제출하세요."},actions:["등록 양식을 작성하고 검토하세요.","요청된 신분 및 비자 문서를 업로드하세요.","마감일 전에 등록 예치금을 납부하세요."],source:"유학생 지원실\n\n2026년 8월 28일까지 작성된 등록 양식과 모든 증빙 문서를 제출하세요. 등록 예치금도 같은 날짜까지 입금되어야 합니다. 2026년 9월 3일 오리엔테이션 참석은 필수입니다."},
    {icon:"⌂",type:"주거 안내",title:"소득 확인 요청",card:"안내문 수령일을 기준으로 한 마감일",summary:"안내문을 받은 날부터 영업일 기준 10일 이내에 소득 확인 양식을 제출하세요.",plain:"주거 담당 부서에서 최신 소득 증명을 요청합니다. 정확한 마감일은 안내문 수령일에 따라 달라집니다.",points:["답변 기한은 영업일 기준 10일입니다.","최근 급여 명세서 또는 복지 급여 증명서를 제출할 수 있습니다.","기한을 넘기면 신청 처리가 지연될 수 있습니다."],deadline:{date:"수령 후 영업일 기준 10일",action:"양식과 최신 소득 증명을 제출하세요."},actions:["안내문을 받은 날짜를 기록하세요.","최신 소득 문서를 준비하세요.","영업일 기준 10일 이내에 양식을 제출하세요."],source:"소득 확인 요청\n\n이 안내문을 받은 날부터 영업일 기준 10일 이내에 동봉된 양식과 최근 급여 명세서 두 장 또는 최신 복지 급여 확인서를 제출하세요. 답변하지 않으면 주거 신청 처리가 지연될 수 있습니다."}
  ]
};

const localeSelect = document.querySelector("#locale-select");
const exampleGrid = document.querySelector("#example-grid");
const result = document.querySelector("#result");
let locale = detectLocale();
let activeDocument = null;

function detectLocale() {
  let saved = null;
  try { saved = localStorage.getItem("comprendoc-demo-locale"); } catch { /* Storage can be disabled in private browsing. */ }
  if (locales.includes(saved)) return saved;
  for (const tag of navigator.languages || [navigator.language]) {
    const normalized = tag.toLowerCase().replaceAll("_", "-");
    if (normalized.startsWith("zh") && /-(tw|hk|mo|hant)(-|$)/.test(normalized)) return "zh-TW";
    if (normalized.startsWith("zh")) return "zh-CN";
    const match = locales.find((item) => item.toLowerCase().split("-")[0] === normalized.split("-")[0]);
    if (match) return match;
  }
  return "en";
}

function escapeHtml(value) {
  return String(value).replace(/[&<>'"]/g, (character) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
}

function renderLanguageOptions() {
  const names = new Intl.DisplayNames([locale], { type: "language" });
  localeSelect.innerHTML = locales.map((code) => `<option value="${code}">${escapeHtml(names.of(code) || code)}</option>`).join("");
  localeSelect.value = locale;
  localeSelect.setAttribute("aria-label", copy[locale].language);
}

function renderExamples() {
  exampleGrid.innerHTML = documents[locale].map((item, index) => `<button class="example-card" type="button" data-document="${index}"><span class="example-card-icon" aria-hidden="true">${item.icon}</span><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.card)}</p></div><span aria-hidden="true">→</span><span class="sr-only">${escapeHtml(copy[locale].open)}</span></button>`).join("");
  exampleGrid.querySelectorAll("[data-document]").forEach((button) => button.addEventListener("click", () => showDocument(Number(button.dataset.document))));
}

function renderResult(index, shouldScroll = true) {
  const item = documents[locale][index];
  const t = copy[locale];
  result.innerHTML = `<div class="result-top"><button class="back-button" type="button" id="back-to-examples">← ${escapeHtml(t.back)}</button><span class="result-status">✓ ${escapeHtml(t.processed)}</span></div><div class="result-hero"><span class="document-type">${escapeHtml(item.type)}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.summary)}</p></div><div class="result-grid"><div class="result-main"><section class="panel"><div class="panel-head"><span class="panel-icon" aria-hidden="true">i</span><div><span class="result-eyebrow">${escapeHtml(t.what)}</span><h3>${escapeHtml(t.plain)}</h3></div></div><p class="summary">${escapeHtml(item.plain)}</p></section><section class="panel"><div class="panel-head"><span class="panel-icon" aria-hidden="true">✓</span><div><span class="result-eyebrow">${escapeHtml(t.know)}</span><h3>${escapeHtml(t.important)}</h3></div></div><ul class="check-list">${item.points.map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul></section><section class="panel"><div class="panel-head"><span class="panel-icon" aria-hidden="true">!</span><div><span class="result-eyebrow">${escapeHtml(t.deadlines)}</span><h3>${escapeHtml(item.deadline.date)}</h3></div></div><div class="deadline"><small>${escapeHtml(t.deadlines)}</small><h4>${escapeHtml(item.deadline.date)}</h4><p>${escapeHtml(item.deadline.action)}</p></div></section><section class="panel"><div class="panel-head"><span class="panel-icon" aria-hidden="true">→</span><div><span class="result-eyebrow">${escapeHtml(t.next)}</span><h3>${escapeHtml(t.actions)}</h3></div></div><ol class="action-list">${item.actions.map((action) => `<li>${escapeHtml(action)}</li>`).join("")}</ol></section><section class="panel"><button class="source-toggle" type="button" id="source-toggle" aria-expanded="false"><span><span class="result-eyebrow">${escapeHtml(t.source)}</span><br><strong>${escapeHtml(t.showSource)}</strong></span><span aria-hidden="true">⌄</span></button><p class="source-text" id="source-text" hidden>${escapeHtml(item.source)}</p></section></div><aside class="result-aside"><section class="aside"><strong>${escapeHtml(t.check)}</strong><p>${escapeHtml(t.checkCopy)}</p></section><section class="aside safe"><strong>${escapeHtml(t.private)}</strong><p>${escapeHtml(t.privateCopy)}</p></section></aside></div>`;
  result.hidden = false;
  result.querySelector("#back-to-examples").addEventListener("click", () => { result.hidden = true; activeDocument = null; document.querySelector("#examples-title").scrollIntoView({behavior:"smooth"}); });
  const toggle = result.querySelector("#source-toggle");
  const source = result.querySelector("#source-text");
  toggle.addEventListener("click", () => { const open = source.hidden; source.hidden = !open; toggle.setAttribute("aria-expanded", String(open)); toggle.querySelector("strong").textContent = open ? t.hideSource : t.showSource; });
  if (shouldScroll) result.scrollIntoView({ behavior: "smooth", block: "start" });
}

function showDocument(index) { activeDocument = index; renderResult(index); }

function applyLocale() {
  const t = copy[locale];
  document.documentElement.lang = locale;
  document.documentElement.dir = "ltr";
  document.title = `Comprendoc — ${t.demo}`;
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t[element.dataset.i18n]; });
  document.querySelectorAll("[data-i18n-aria]").forEach((element) => { element.setAttribute("aria-label", t[element.dataset.i18nAria]); });
  renderLanguageOptions();
  renderExamples();
  if (activeDocument !== null) renderResult(activeDocument, false);
}

localeSelect.addEventListener("change", () => { locale = localeSelect.value; try { localStorage.setItem("comprendoc-demo-locale", locale); } catch { /* Language still applies for this page view. */ } applyLocale(); });
applyLocale();
